CREATE TABLE DCF_RAWDATA.STAGING.STG_PERSONS
LIKE DCF_RAWDATA.PUBLIC.T_PERSONS;

ALTER TABLE DCF_RAWDATA.STAGING.STG_PERSONS
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);


CREATE TABLE DCF_RAWDATA.STAGING.STG_CASES
LIKE DCF_RAWDATA.PUBLIC.T_CASES;

ALTER TABLE DCF_RAWDATA.STAGING.STG_CASES
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);


CREATE TABLE DCF_RAWDATA.STAGING.STG_MEDICATIONS
LIKE DCF_RAWDATA.PUBLIC.T_MEDICATIONS;

ALTER TABLE DCF_RAWDATA.STAGING.STG_MEDICATIONS
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);

CREATE TABLE DCF_RAWDATA.STAGING.STG_MEDICATION_HEALTH_BEHAVIOR
LIKE DCF_RAWDATA.PUBLIC.T_MEDICATION_HEALTH_BEHAVIOR;

ALTER TABLE DCF_RAWDATA.STAGING.STG_MEDICATION_HEALTH_BEHAVIOR
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);


CREATE TABLE DCF_RAWDATA.STAGING.STG_CUSTODIES
LIKE DCF_RAWDATA.PUBLIC.T_CUSTODIES;

ALTER TABLE DCF_RAWDATA.STAGING.STG_CUSTODIES
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);

CREATE TABLE DCF_RAWDATA.STAGING.STG_PERSON_ORG_INVOLVEMENT
LIKE DCF_RAWDATA.PUBLIC.T_PERSON_ORG_INVOLVEMENT;

ALTER TABLE DCF_RAWDATA.STAGING.STG_PERSON_ORG_INVOLVEMENT
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);

CREATE TABLE DCF_RAWDATA.STAGING.STG_PERSON_ROLE_ASSIGNMENTS
LIKE DCF_RAWDATA.PUBLIC.T_PERSON_ROLE_ASSIGNMENTS;

ALTER TABLE DCF_RAWDATA.STAGING.STG_PERSON_ROLE_ASSIGNMENTS
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);

CREATE TABLE DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES
LIKE DCF_RAWDATA.PUBLIC.T_ALLOWABLE_VALUES;

ALTER TABLE DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES
ADD COLUMN STAGING_LOADED_TIMESTAMP TIMESTAMP_NTZ(9);


CREATE TABLE DCF_RAWDATA.STAGING.INVALID_RECORDS
(
    TABLE_NAME                 VARCHAR,
    FILE_NAME                  VARCHAR,
    PRIMARY_KEY_VALUE          VARCHAR,
    ERROR_REASON               VARCHAR,
    ROW_DATA                   VARIANT,
    INVALID_RECORD_TIMESTAMP   TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_PERSONS
ON TABLE DCF_RAWDATA.PUBLIC.T_PERSONS
SHOW_INITIAL_ROWS = TRUE;


CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_CASES
ON TABLE DCF_RAWDATA.PUBLIC.T_CASES
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_MEDICATIONS
ON TABLE DCF_RAWDATA.PUBLIC.T_MEDICATIONS
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_MEDICATION_HEALTH_BEHAVIOR
ON TABLE DCF_RAWDATA.PUBLIC.T_MEDICATION_HEALTH_BEHAVIOR
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_CUSTODIES
ON TABLE DCF_RAWDATA.PUBLIC.T_CUSTODIES
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_PERSON_ORG_INVOLVEMENT
ON TABLE DCF_RAWDATA.PUBLIC.T_PERSON_ORG_INVOLVEMENT
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_PERSON_ROLE_ASSIGNMENTS
ON TABLE DCF_RAWDATA.PUBLIC.T_PERSON_ROLE_ASSIGNMENTS
SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM DCF_RAWDATA.PUBLIC.STREAM_T_ALLOWABLE_VALUES
ON TABLE DCF_RAWDATA.PUBLIC.T_ALLOWABLE_VALUES
SHOW_INITIAL_ROWS = TRUE;


delete  from STAGING.STG_PERSON_ROLE_ASSIGNMENTS

select * from dcf_rawdata.public.STREAM_T_PERSON_ROLE_ASSIGNMENTS




ALTER TABLE DCF_RAWDATA.STAGING.STG_PERSONS
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_CASES
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_MEDICATIONS
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_MEDICATION_HEALTH_BEHAVIOR
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_CUSTODIES
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_PERSON_ORG_INVOLVEMENT
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_PERSON_ROLE_ASSIGNMENTS
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;

ALTER TABLE DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES
RENAME COLUMN LOAD_TIMESTAMP TO RAW_LOAD_TIMESTAMP;


select * from DCF_RAWDATA.PUBLIC.STREAM_T_PERSONS

select * from AUDIT.AUDIT_JOB_LOG order by end_time desc



SELECT GET_DDL('SCHEMA', 'DCF_RAWDATA.STAGING');
SELECT GET_DDL('SCHEMA', 'DCF_RAWDATA.PUBLIC');



TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_CASES;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_CUSTODIES;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_MEDICATIONS;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_MEDICATION_HEALTH_BEHAVIOR;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_PERSONS;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_PERSON_ORG_INVOLVEMENT;
TRUNCATE TABLE DCF_RAWDATA.STAGING.STG_PERSON_ROLE_ASSIGNMENTS;