# Database & Warehouse
DB = "DCF_RAWDATA"
WH = "COMPUTE_WH"


# Schemas
RAW = "PUBLIC"
RAWDATA = "RAWDATA"
STG = "STAGING"
DWH = "DWH"
CONFIG = "CONFIG"
AUDIT = "AUDIT"
UTIL = "UTIL"

# Raw Tables
T_ALLOWABLE_VALUES = "T_ALLOWABLE_VALUES"
T_CASES = "T_CASES"
T_CUSTODIES = "T_CUSTODIES"
T_MEDICATIONS = "T_MEDICATIONS"
T_MEDICATION_HEALTH_BEHAVIOR = "T_MEDICATION_HEALTH_BEHAVIOR"
T_PERSON_ORG_INVOLVEMENT = "T_PERSON_ORG_INVOLVEMENT"
T_PERSON_ROLE_ASSIGNMENTS = "T_PERSON_ROLE_ASSIGNMENTS"
T_PERSONS = "T_PERSONS"

# Streams
STREAM_T_ALLOWABLE_VALUES = "STREAM_T_ALLOWABLE_VALUES"
STREAM_T_CASES = "STREAM_T_CASES"
STREAM_T_CUSTODIES = "STREAM_T_CUSTODIES"
STREAM_T_MEDICATIONS = "STREAM_T_MEDICATIONS"
STREAM_T_MEDICATION_HEALTH_BEHAVIOR = "STREAM_T_MEDICATION_HEALTH_BEHAVIOR"
STREAM_T_PERSON_ORG_INVOLVEMENT = "STREAM_T_PERSON_ORG_INVOLVEMENT"
STREAM_T_PERSON_ROLE_ASSIGNMENTS = "STREAM_T_PERSON_ROLE_ASSIGNMENTS"
STREAM_T_PERSONS = "STREAM_T_PERSONS"

# Staging Tables
STG_ALLOWABLE_VALUES = "STG_ALLOWABLE_VALUES"
STG_CASES = "STG_CASES"
STG_CUSTODIES = "STG_CUSTODIES"
STG_MEDICATIONS = "STG_MEDICATIONS"
STG_MEDICATION_HEALTH_BEHAVIOR = "STG_MEDICATION_HEALTH_BEHAVIOR"
STG_PERSON_ORG_INVOLVEMENT = "STG_PERSON_ORG_INVOLVEMENT"
STG_PERSON_ROLE_ASSIGNMENTS = "STG_PERSON_ROLE_ASSIGNMENTS"
STG_PERSONS = "STG_PERSONS"
INVALID_RECORDS = "INVALID_RECORDS"

# DWH Tables
DIM_CASES_INFO = "DIM_CASES_INFO"
DIM_CUSTODIES_INFO = "DIM_CUSTODIES_INFO"
DIM_MEDICATIONS_INFO = "DIM_MEDICATIONS_INFO"
DIM_MEDICATION_HEALTH_BEHAVIOR_INFO = "DIM_MEDICATION_HEALTH_BEHAVIOR_INFO"
DIM_PERSON_ORG_INVOLVEMENT_INFO = "DIM_PERSON_ORG_INVOLVEMENT_INFO"
DIM_PERSON_ROLE_ASSIGNMENTS_INFO = "DIM_PERSON_ROLE_ASSIGNMENTS_INFO"
DIM_T_PERSONS = "DIM_T_PERSONS"

#Fact tables
FACT_CASES = "FACT_CASES"
FACT_CUSTODIES = "FACT_CUSTODIES"
FACT_MEDICATIONS = "FACT_MEDICATIONS"
FACT_MEDICATION_HEALTH_BEHAVIOR = "FACT_MEDICATION_HEALTH_BEHAVIOR"
FACT_PERSON_ORG_INVOLVEMENT = "FACT_PERSON_ORG_INVOLVEMENT"
FACT_PERSON_ROLE_ASSIGNMENTS = "FACT_PERSON_ROLE_ASSIGNMENTS"

# Config Tables
TABLE_PK_CONFIG = "TABLE_PK_CONFIG"
ETL_WATERMARK = "ETL_WATERMARK"
ETL_FAILED_RECORDS = "ETL_FAILED_RECORDS"

# Stored Procedures audit&mail
SP_LOG_AUDIT = "SP_LOG_AUDIT"
SP_SEND_PIPELINE_NOTIFICATION = "SP_SEND_PIPELINE_NOTIFICATION"
SP_ORCHESTRATE_RAW_LOAD = "SP_ORCHESTRATE_RAW_LOAD"
SP_LOAD_RAW_TABLE = "SP_LOAD_RAW_TABLE"

# Stages and File Formats
POSTGRES_STAGE = "POSTGRES_STAGE"
STREAM_POSTGRES_STAGE = "STREAM_POSTGRES_STAGE"
CSV_FILE_FORMAT = "CSV_FILE_FORMAT"