

USE DATABASE DCF_RAWDATA;
USE SCHEMA UTIL;

CREATE OR REPLACE PROCEDURE DCF_RAWDATA.UTIL.SP_ORCHESTRATE_STG_DWH()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    LET result STRING := '';

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_ALLOWABLE_VALUES')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_ALLOWABLE_VALUES();
        result := result || 'AV|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_PERSONS')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_PERSONS();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_T_PERSONS();
        result := result || 'PERSONS|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_MEDICATIONS')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_MEDICATIONS();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_MEDICATIONS_INFO();
        CALL DCF_RAWDATA.DWH.SP_DWH_FACT_MEDICATIONS();
        result := result || 'MEDS|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_CASES')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_CASES();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_CASES_INFO();
        CALL DCF_RAWDATA.DWH.SP_DWH_FACT_CASES();
        result := result || 'CASES|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_PERSON_ORG_INVOLVEMENT')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_PERSON_ORG_INVOLVEMENT();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_PERSON_ORG_INVOLVEMENT_INFO();
        CALL DCF_RAWDATA.DWH.SP_DWH_FACT_PERSON_ORG_INVOLVEMENT();
        result := result || 'POI|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_CUSTODIES')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_CUSTODIES();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_CUSTODIES_INFO();
        CALL DCF_RAWDATA.DWH.SP_DWH_FACT_CUSTODIES();
        result := result || 'CUSTODIES|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_PERSON_ROLE_ASSIGNMENTS')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_PERSON_ROLE_ASSIGNMENTS();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_PERSON_ROLE_ASSIGNMENTS_INFO();
        CALL DCF_RAWDATA.DWH.SP_DWH_FACT_PERSON_ROLE_ASSIGNMENTS();
        result := result || 'PRA|';
    END IF;

    IF (SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_T_MEDICATION_HEALTH_BEHAVIOR')) THEN
        CALL DCF_RAWDATA.STAGING.SP_STG_MEDICATION_HEALTH_BEHAVIOR();
        CALL DCF_RAWDATA.DWH.SP_DWH_DIM_MEDICATION_HEALTH_BEHAVIOR_INFO();
        CALL DCF_RAWDATA.DWH.SP_DWH_FACT_MEDICATION_HEALTH_BEHAVIOR();
        result := result || 'MHB|';
    END IF;

    IF (result = '') THEN
        RETURN 'NO_DATA: All streams empty';
    END IF;

    RETURN 'COMPLETED: ' || result;
END;

CREATE OR REPLACE TASK DCF_RAWDATA.UTIL.TASK_RAW_ORCHESTRATE
  WAREHOUSE = 'COMPUTE_WH'
  SCHEDULE = '10 MINUTE'
  TASK_AUTO_RETRY_ATTEMPTS = 3
  WHEN SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_POSTGRES_STAGE')
AS
  CALL DCF_RAWDATA.PUBLIC.SP_ORCHESTRATE_RAW_LOAD();

CREATE OR REPLACE TASK DCF_RAWDATA.UTIL.TASK_STG_DWH_ORCHESTRATE
  WAREHOUSE = 'COMPUTE_WH'
  TASK_AUTO_RETRY_ATTEMPTS = 3
  AFTER DCF_RAWDATA.UTIL.TASK_RAW_ORCHESTRATE
AS
  CALL DCF_RAWDATA.UTIL.SP_ORCHESTRATE_STG_DWH();

ALTER TASK DCF_RAWDATA.UTIL.TASK_STG_DWH_ORCHESTRATE RESUME;
ALTER TASK DCF_RAWDATA.UTIL.TASK_RAW_ORCHESTRATE RESUME;

-- SELECT * FROM TABLE(DCF_RAWDATA.INFORMATION_SCHEMA.TASK_HISTORY()) ORDER BY SCHEDULED_TIME DESC LIMIT 20;
