CREATE OR REPLACE TASK DCF_RAWDATA.UTIL.TASK_RAW_ORCHESTRATE
  WAREHOUSE = 'COMPUTE_WH'
  SCHEDULE = '5 MINUTE'
  TASK_AUTO_RETRY_ATTEMPTS = 3
  WHEN SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_POSTGRES_STAGE')
AS
  CALL DCF_RAWDATA.PUBLIC.SP_ORCHESTRATE_RAW_LOAD();


  

CREATE OR REPLACE TASK DCF_RAWDATA.UTIL.MAIN_TASK
  WAREHOUSE = 'COMPUTE_WH'
  AFTER DCF_RAWDATA.UTIL.TASK_RAW_ORCHESTRATE
AS
  EXECUTE NOTEBOOK PROJECT DCF_RAWDATA.UTIL.STAGING_PROJECT
    MAIN_FILE = 'DWH/final_pipeline.ipynb'
    COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
    QUERY_WAREHOUSE = 'COMPUTE_WH'
    RUNTIME = 'V2.7-CPU-PY3.12';
    

ALTER TASK DCF_RAWDATA.UTIL.MAIN_TASK RESUME;
ALTER TASK DCF_RAWDATA.UTIL.TASK_RAW_ORCHESTRATE RESUME;