create or replace schema DWH;

create or replace TABLE DIM_CASES_INFO (
	CASES_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	CASE_TYPE_DESC VARCHAR(80),
	CASE_TYPE_AV_ID VARCHAR(10),
	CURRENT_CASE_STATUS_CODE_DESC VARCHAR(80),
	CURRENT_CASE_STATUS_CODE_AV_ID VARCHAR(10),
	RESTRICTION_REASON_CODE_DESC VARCHAR(80),
	RESTRICTION_REASON_CODE_AV_ID VARCHAR(10),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	primary key (CASES_INFO_ID)
);
create or replace TABLE DIM_CUSTODIES_INFO (
	CUSTODIES_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	LEGAL_STATUS_CODE_DESC VARCHAR(80),
	LEGAL_STATUS_CODE_AV_ID VARCHAR(10),
	END_REASON_CODE_DESC VARCHAR(80),
	END_REASON_CODE_AV_ID VARCHAR(10),
	CUSTODY_TYPE_DESC VARCHAR(80),
	CUSTODY_TYPE_AV_ID VARCHAR(10),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(255),
	primary key (CUSTODIES_INFO_ID)
);
create or replace TABLE DIM_MEDICATIONS_INFO (
	MEDICATIONS_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	MEDICATION_CLASSIFICATION_CODE_AV_ID VARCHAR(10),
	MEDICATION_CLASSIFICATION_CODE_DESC VARCHAR(80),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	primary key (MEDICATIONS_INFO_ID)
);
create or replace TABLE DIM_MEDICATION_HEALTH_BEHAVIOR_INFO (
	MEDICATION_HEALTH_BEHAVIOR_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	PRESCRIBED_FREQUENCY_CODE_AV_ID VARCHAR(10),
	PRESCRIBED_FREQUENCY_CODE_DESC VARCHAR(80),
	ADMINISTER_METHOD_CODE_AV_ID VARCHAR(10),
	ADMINISTER_METHOD_CODE_DESC VARCHAR(80),
	CONSENT_DECISION_CODE_AV_ID VARCHAR(10),
	CONSENT_DECISION_CODE_DESC VARCHAR(80),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	primary key (MEDICATION_HEALTH_BEHAVIOR_INFO_ID)
);
create or replace TABLE DIM_PERSON_ORG_INVOLVEMENT_INFO (
	PERSON_ORG_INVOLVEMENT_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	REASON_CLOSED_CODE_AV_ID VARCHAR(10),
	REASON_CLOSED_CODE_DESC VARCHAR(80),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(100),
	primary key (PERSON_ORG_INVOLVEMENT_INFO_ID)
);
create or replace TABLE DIM_PERSON_ROLE_ASSIGNMENTS_INFO (
	PERSON_ROLE_ASSIGNMENTS_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	ROLE_TYPE_DESC VARCHAR(80),
	ROLE_TYPE_AV_ID VARCHAR(10),
	ROLE_SUB_TYPE_DESC VARCHAR(80),
	ROLE_SUB_TYPE_AV_ID VARCHAR(10),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	DELETED_DATE TIMESTAMP_NTZ(9),
	primary key (PERSON_ROLE_ASSIGNMENTS_INFO_ID)
);
create or replace TABLE DIM_STAFF_PERSON_OFFICE_ASSIGNS_INFO (
	STAFF_PERSON_OFFICE_ASSIGNS_INFO_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	ASSIGNMENT_TYPE_DESC VARCHAR(80),
	ASSIGNMENT_TYPE_AV_ID VARCHAR(10),
	ASSIGNMENT_SUB_TYPE_DESC VARCHAR(80),
	ASSIGNMENT_SUB_TYPE_AV_ID VARCHAR(10),
	JBPM_PROCESS_OUTCOME_CODE_DESC VARCHAR(80),
	JBPM_PROCESS_OUTCOME_CODE_AV_ID VARCHAR(10),
	WORKLOAD_TYPE_DESC VARCHAR(80),
	WORKLOAD_TYPE_AV_ID VARCHAR(80),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	primary key (STAFF_PERSON_OFFICE_ASSIGNS_INFO_ID)
);
create or replace TABLE DIM_T_PERSONS (
	PER_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	PERSON_ID NUMBER(10,0) NOT NULL,
	LAST_NAME VARCHAR(25),
	FULL_NAME VARCHAR(50),
	CITIZENSHIP_CODE_AV_ID VARCHAR(10),
	CITIZENSHIP_CODE_DESC VARCHAR(80),
	PRIMARY_LANGUAGE_CODE_AV_ID VARCHAR(10),
	PRIMARY_LANGUAGE_CODE_DESC VARCHAR(80),
	DO_NOT_RESUSCITATE_IND VARCHAR(1),
	EDUCATIONAL_PARENT_IND VARCHAR(1),
	GUARDIANSHIP_CONSENT_IND VARCHAR(1),
	ADOPTION_NOT_APPROPRIATE_IND VARCHAR(1),
	BIO_PARENTS_RETURN_IND VARCHAR(1),
	BIRTH_CERTIFICATE_AVLBL_IND VARCHAR(1),
	NO_PHONE_IND VARCHAR(1),
	PET_OWNER_IND VARCHAR(1),
	SMOKER_IND VARCHAR(1),
	SSN_VALIDATION_IND VARCHAR(1),
	RESTRICTED_IND VARCHAR(1),
	ADOPTION_MATCH_FOUND_IND VARCHAR(1),
	MARITAL_STATUS_CODE_AV_ID VARCHAR(10),
	MARITAL_STATUS_CODE_DESC VARCHAR(80),
	PREFIX_CODE_AV_ID VARCHAR(10),
	PREFIX_CODE_DESC VARCHAR(80),
	FIRST_NAME VARCHAR(15),
	MIDDLE_NAME VARCHAR(35),
	SUFFIX_CODE_AV_ID VARCHAR(10),
	SUFFIX_CODE_DESC VARCHAR(80),
	PROFESSIONAL_SUFFIX_CODE_AV_ID VARCHAR(10),
	PROFESSIONAL_SUFFIX_CODE_DESC VARCHAR(80),
	AGE_NUM NUMBER(38,0),
	AGE_UNIT_CODE_AV_ID VARCHAR(10),
	AGE_UNIT_CODE_DESC VARCHAR(80),
	BIRTH_DATE TIMESTAMP_NTZ(9),
	CURRENT_AGE NUMBER(10,0),
	BIRTH_PLACE_STATE_CODE_AV_ID VARCHAR(10),
	BIRTH_PLACE_STATE_DESC VARCHAR(80),
	BIRTH_PLACE_CITY_NAME VARCHAR(35),
	BIRTH_PLACE_HOSPITAL_NAME VARCHAR(35),
	BIRTH_PLACE_COUNTRY_CODE_AV_ID VARCHAR(10),
	BIRTH_PLACE_COUNTRY_CODE_DESC VARCHAR(80),
	DECEASED_DATE TIMESTAMP_NTZ(9),
	DECEASED_COUNTRY_CODE_AV_ID VARCHAR(10),
	DECEASED_COUNTRY_CODE_DESC VARCHAR(80),
	DECEASED_CITY_NAME VARCHAR(35),
	DECEASED_STATE_CODE_AV_ID VARCHAR(10),
	DECEASED_STATE_CODE_DESC VARCHAR(80),
	ALIEN_REGISTRATION_NUM VARCHAR(15),
	CURRENT_GRADE_CODE_AV_ID VARCHAR(10),
	CURRENT_GRADE_CODE_DESC VARCHAR(80),
	ETHNICITY_CODE_AV_ID VARCHAR(10),
	ETHNICITY_CODE_DESC VARCHAR(80),
	GENDER_CODE_AV_ID VARCHAR(10),
	GENDER_CODE_DESC VARCHAR(80),
	IMMIGRATION_STATUS_CODE_AV_ID VARCHAR(10),
	IMMIGRATION_STATUS_CODE_DESC VARCHAR(80),
	OCCUPATION_DESC VARCHAR(80),
	RACE_CODE_AV_ID VARCHAR(10),
	RACE_CODE_DESC VARCHAR(80),
	RELIGION_CODE_AV_ID VARCHAR(10),
	RELIGION_CODE_DESC VARCHAR(80),
	SOCIAL_SECURITY_NUM VARCHAR(9),
	SSN_SOURCE_CODE_AV_ID VARCHAR(10),
	SSN_SOURCE_CODE_DESC VARCHAR(80),
	SSN_REFUSAL_DATE TIMESTAMP_NTZ(9),
	BIRTH_ORDER_SEQUENCE_NUM NUMBER(38,0),
	MARITAL_STATUS_EFFECT_DATE TIMESTAMP_NTZ(9),
	COMMON_CLIENT_ID NUMBER(10,0),
	CHILD_ADOPTED_CODE_AV_ID VARCHAR(10),
	CHILD_ADOPTED_CODE_DESC VARCHAR(80),
	AGE_CHILD_ADOPTED_NUM NUMBER(38,0),
	AGE_CHILD_ADP_UNIT_CODE_AV_ID VARCHAR(10),
	AGE_CHILD_ADP_UNIT_CODE_DESC VARCHAR(80),
	GESTATIONAL_AGE_NUM NUMBER(38,0),
	US_ENTRY_DATE TIMESTAMP_NTZ(9),
	ADOPTION_FREED_DATE TIMESTAMP_NTZ(9),
	ARCHIVE_DATE TIMESTAMP_NTZ(9),
	ARCHIVE_FILE_NAME VARCHAR(75),
	LAST_ELECTRON_RETRIEVAL_DATE TIMESTAMP_NTZ(9),
	PERSON_PERSON_REQUESTS_ID NUMBER(10,0),
	AFCARS_ADOPTION_SEND_DATE TIMESTAMP_NTZ(9),
	DUP_PERSON_STATUS_CODE_AV_ID VARCHAR(10),
	DUP_PERSON_STATUS_CODE_DESC VARCHAR(80),
	PERSON_PERSON_PRIMARY_ID NUMBER(10,0),
	APPROXIMATE_DOB_IND VARCHAR(1),
	CHILD_ADOPTED_DATE TIMESTAMP_NTZ(9),
	APPROX_LAST_ADOPTED_DATE_IND VARCHAR(1),
	ITIN_NUM VARCHAR(9),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(333),
	DELETED_DATE TIMESTAMP_NTZ(9),
	primary key (PER_ID)
);
create or replace TABLE FACT_CASES (
	ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	CAS_ID NUMBER(10,0),
	CASE_NAME VARCHAR(35),
	CASES_INFO_ID NUMBER(10,0),
	RESTRICTED_IND VARCHAR(1),
	CASE_ACCESS_IND VARCHAR(1),
	ASSIST_CAS_NUM NUMBER(10,0),
	EXPECTED_CLOSE_DATE TIMESTAMP_NTZ(9),
	UNIT_ORGN_ID NUMBER(10,0),
	AREA_ORGN_ID NUMBER(10,0),
	REGION_ORGN_ID NUMBER(10,0),
	CURRENT_CASE_STATUS_DATE TIMESTAMP_NTZ(9),
	RESTRICTION_DATE TIMESTAMP_NTZ(9),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	primary key (ID)
);
create or replace TABLE FACT_CUSTODIES (
	ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	CUS_ID NUMBER(10,0),
	CUSTODIES_INFO_ID NUMBER(10,0),
	TWENTY_NINE_C_IND VARCHAR(1),
	START_DATE TIMESTAMP_NTZ(9),
	PERSON_PERSON_ID NUMBER(10,0),
	ORGN_ORGN_ID NUMBER(10,0),
	VPA_VPA_ID NUMBER(10,0),
	SUR_SUR_ID NUMBER(10,0),
	CAP_CAP_ID NUMBER(10,0),
	POI_POI_ID NUMBER(10,0),
	CHILD_ADJUDICATED_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9),
	TWENTY_NINE_C_DATE TIMESTAMP_NTZ(9),
	REASONABLE_EFFORT_DATE TIMESTAMP_NTZ(9),
	PERSON_PERSON_CHILD_ID NUMBER(10,0),
	MOD_CAP_CAP_ID NUMBER(10,0),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(255),
	primary key (ID)
);
create or replace TABLE FACT_MEDICATIONS (
	ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	MED_ID NUMBER(10,0),
	MEDICATIONS_INFO_ID NUMBER(10,0),
	COMMON_NAME VARCHAR(80),
	ROGER_DECISION_DRUG_IND VARCHAR(1),
	MEDICATION_DESC VARCHAR(80),
	ALLOW_FREQUENCY_NUM NUMBER(38,0),
	ADD_PERSON_ID NUMBER(10,0),
	ADD_ORGN_ID NUMBER(10,0),
	MOD_PERSON_ID NUMBER(10,0),
	MOD_ORGN_ID NUMBER(10,0),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	primary key (ID)
);
create or replace TABLE FACT_MEDICATION_HEALTH_BEHAVIOR (
	ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	MHP_ID NUMBER(10,0),
	MEDICATION_HEALTH_BEHAVIOR_INFO_ID NUMBER(10,0),
	HPP_HPP_ID NUMBER(10,0),
	MED_MED_ID NUMBER(10,0),
	PERSON_PERSON_PATIENT_ID NUMBER(10,0),
	PERSON_PERSON_PRESCRIBER_ID NUMBER(10,0),
	PRESCRIBER_PCS_PCS_ID NUMBER(10,0),
	CONSENT_BY_PERSON_PERSON_ID NUMBER(10,0),
	DOSAGE_DESC VARCHAR(80),
	START_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9),
	DATE_UNKNOWN VARCHAR(1),
	CONSENT_DATE TIMESTAMP_NTZ(9),
	CONSENT_COMMENTS VARCHAR(4000),
	LAST_REFILL_DATE TIMESTAMP_NTZ(9),
	MEDICATION_CMNT VARCHAR(2000),
	CLN_RESP_ADVERSE_EFFECT_CMNT VARCHAR(150),
	THRIVE_FAILURE_IND VARCHAR(1),
	ADD_ORGN_ID NUMBER(10,0),
	ADD_PERSON_ID NUMBER(10,0),
	MOD_ORGN_ID NUMBER(10,0),
	MOD_PERSON_ID NUMBER(10,0),
	CREATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	primary key (ID)
);
create or replace TABLE FACT_PERSON_ORG_INVOLVEMENT (
	ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	POI_ID NUMBER(10,0),
	IC_IC_ID NUMBER(10,0),
	CAS_CAS_ID NUMBER(10,0),
	INV_INV_ID NUMBER(10,0),
	ORGN_ORGN_ID NUMBER(10,0),
	PERSON_PERSON_ID NUMBER(10,0),
	START_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9),
	PERSON_ORG_INVOLVEMENT_INFO_ID NUMBER(10,0),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99),
	SEARCHED_IND VARCHAR(2),
	primary key (ID)
);
create or replace TABLE FACT_PERSON_ROLE_ASSIGNMENTS (
	ID NUMBER(10,0) autoincrement start 1 increment 1 order,
	PRA1_ID NUMBER(10,0),
	POI_POI_ID NUMBER(10,0),
	PERSON_ROLE_ASSIGNMENTS_INFO_ID NUMBER(10,0),
	START_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	DELETED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(99)
);
create or replace TABLE FACT_STAFF_PERSON_OFFICE_ASSIGNS (
	ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 order,
	SPAS_ID NUMBER(10,0),
	STAFF_PERSON_OFFICE_ASSIGNS_INFO_ID NUMBER(10,0),
	NEW_ASSIGNMENT_IND VARCHAR(1),
	SP_SP_ID NUMBER(10,0),
	IC_IC_ID NUMBER(10,0),
	INV_INV_ID NUMBER(10,0),
	CAS_CAS_ID NUMBER(10,0),
	ASM_ASM_ID NUMBER(10,0),
	RE_RE_ID NUMBER(10,0),
	CRT_CRT_ID NUMBER(10,0),
	CONTEXT_ID NUMBER(10,0),
	PERSON_PERSON_ID NUMBER(10,0),
	APPROVAL_ID NUMBER(10,0),
	ORGN_ORGN_DSS_ID NUMBER(10,0),
	ORGN_ORGN_EXTERNAL_ID NUMBER(10,0),
	ASSIGNMENT_START_DATE TIMESTAMP_NTZ(9),
	ASSIGNMENT_END_DATE TIMESTAMP_NTZ(9),
	UNIT_ORGN_ID NUMBER(10,0),
	AREA_ORGN_ID NUMBER(10,0),
	REGION_ORGN_ID NUMBER(10,0),
	IVED_IVED_ID NUMBER(10,0),
	FAMILY_RESO_HOME_ORGN_ORGN_ID NUMBER(10,0),
	DIVISION_ORGN_ORGN_ID NUMBER(10,0),
	PROVIDER_AGENCY_ORGN_ID NUMBER(10,0),
	NON_DSS_ASSIGNMENT_IND VARCHAR(1),
	STARS_CONVERSION_IND VARCHAR(1),
	WORKFLOW_ORGN_ID NUMBER(10,0),
	JBPM_PROCESS_INSTANCE_ID NUMBER(10,0),
	JBPM_STATUS_DATE TIMESTAMP_NTZ(9),
	STAFF_PERSON_PERSON_ID_4_WEB NUMBER(10,0),
	ADD_TS TIMESTAMP_NTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_NTZ(9),
	MOD_USER VARCHAR(20),
	CREATED_DATE TIMESTAMP_NTZ(9),
	CHECKSUM VARCHAR(100),
	DELETED_DATE TIMESTAMP_NTZ(9),
	primary key (ID)
);
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_CASES_INFO"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_CASES_INFO_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_CASES AS
        SELECT DISTINCT
            c.CASE_TYPE AS CASE_TYPE_AV_ID, av1.VALUE_SHORT_DESC AS CASE_TYPE_DESC,
            c.CURRENT_CASE_STATUS_CODE AS CURRENT_CASE_STATUS_CODE_AV_ID, av2.VALUE_SHORT_DESC AS CURRENT_CASE_STATUS_CODE_DESC,
            c.RESTRICTION_REASON_CODE AS RESTRICTION_REASON_CODE_AV_ID, av3.VALUE_SHORT_DESC AS RESTRICTION_REASON_CODE_DESC,
            c.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(TO_VARCHAR(c.CASE_TYPE), ''''), COALESCE(av1.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(c.CURRENT_CASE_STATUS_CODE), ''''), COALESCE(av2.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(c.RESTRICTION_REASON_CODE), ''''), COALESCE(av3.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(c.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_CASES c
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av1 ON c.CASE_TYPE = av1.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av2 ON c.CURRENT_CASE_STATUS_CODE = av2.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av3 ON c.RESTRICTION_REASON_CODE = av3.AV_ID;

        UPDATE DCF_RAWDATA.DWH.DIM_CASES_INFO tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_CASES src
        WHERE tgt.CASE_TYPE_AV_ID IS NOT DISTINCT FROM src.CASE_TYPE_AV_ID
          AND tgt.CURRENT_CASE_STATUS_CODE_AV_ID IS NOT DISTINCT FROM src.CURRENT_CASE_STATUS_CODE_AV_ID
          AND tgt.RESTRICTION_REASON_CODE_AV_ID IS NOT DISTINCT FROM src.RESTRICTION_REASON_CODE_AV_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        INSERT INTO DCF_RAWDATA.DWH.DIM_CASES_INFO
        (CASE_TYPE_AV_ID, CASE_TYPE_DESC, CURRENT_CASE_STATUS_CODE_AV_ID, CURRENT_CASE_STATUS_CODE_DESC,
         RESTRICTION_REASON_CODE_AV_ID, RESTRICTION_REASON_CODE_DESC, CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM)
        SELECT src.CASE_TYPE_AV_ID, src.CASE_TYPE_DESC, src.CURRENT_CASE_STATUS_CODE_AV_ID, src.CURRENT_CASE_STATUS_CODE_DESC,
               src.RESTRICTION_REASON_CODE_AV_ID, src.RESTRICTION_REASON_CODE_DESC, CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_CASES src
        WHERE NOT EXISTS (SELECT 1 FROM DCF_RAWDATA.DWH.DIM_CASES_INFO tgt WHERE tgt.CHECKSUM = src.CHECKSUM AND tgt.UPDATED_DATE IS NULL);

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_CASES_INFO load completed. Rows Loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_CASES_INFO load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_CUSTODIES_INFO"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_CUSTODIES_INFO_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_CUSTODIES AS
        SELECT DISTINCT
            c.LEGAL_STATUS_CODE AS LEGAL_STATUS_CODE_AV_ID, av1.VALUE_SHORT_DESC AS LEGAL_STATUS_CODE_DESC,
            c.END_REASON_CODE AS END_REASON_CODE_AV_ID, av2.VALUE_SHORT_DESC AS END_REASON_CODE_DESC,
            c.CUSTODY_TYPE AS CUSTODY_TYPE_AV_ID, av3.VALUE_SHORT_DESC AS CUSTODY_TYPE_DESC,
            c.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(av1.VALUE_SHORT_DESC, ''''), COALESCE(TO_VARCHAR(c.LEGAL_STATUS_CODE), ''''),
                COALESCE(av2.VALUE_SHORT_DESC, ''''), COALESCE(TO_VARCHAR(c.END_REASON_CODE), ''''),
                COALESCE(av3.VALUE_SHORT_DESC, ''''), COALESCE(TO_VARCHAR(c.CUSTODY_TYPE), ''''),
                COALESCE(TO_VARCHAR(c.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_CUSTODIES c
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av1 ON c.LEGAL_STATUS_CODE = av1.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av2 ON c.END_REASON_CODE = av2.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av3 ON c.CUSTODY_TYPE = av3.AV_ID;

        UPDATE DCF_RAWDATA.DWH.DIM_CUSTODIES_INFO tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_CUSTODIES src
        WHERE tgt.LEGAL_STATUS_CODE_AV_ID IS NOT DISTINCT FROM src.LEGAL_STATUS_CODE_AV_ID
          AND tgt.END_REASON_CODE_AV_ID IS NOT DISTINCT FROM src.END_REASON_CODE_AV_ID
          AND tgt.CUSTODY_TYPE_AV_ID IS NOT DISTINCT FROM src.CUSTODY_TYPE_AV_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        INSERT INTO DCF_RAWDATA.DWH.DIM_CUSTODIES_INFO
        (LEGAL_STATUS_CODE_AV_ID, LEGAL_STATUS_CODE_DESC, END_REASON_CODE_AV_ID, END_REASON_CODE_DESC,
         CUSTODY_TYPE_AV_ID, CUSTODY_TYPE_DESC, CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM)
        SELECT src.LEGAL_STATUS_CODE_AV_ID, src.LEGAL_STATUS_CODE_DESC, src.END_REASON_CODE_AV_ID, src.END_REASON_CODE_DESC,
               src.CUSTODY_TYPE_AV_ID, src.CUSTODY_TYPE_DESC, CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_CUSTODIES src
        WHERE NOT EXISTS (SELECT 1 FROM DCF_RAWDATA.DWH.DIM_CUSTODIES_INFO tgt WHERE tgt.CHECKSUM = src.CHECKSUM AND tgt.UPDATED_DATE IS NULL);

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_CUSTODIES_INFO load completed. Rows Loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_CUSTODIES_INFO load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_MEDICATIONS_INFO"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_MEDICATIONS_INFO_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_MEDICATIONS AS
        SELECT DISTINCT
            m.MEDICATION_CLASSIFICATION_CODE AS MEDICATION_CLASSIFICATION_CODE_AV_ID,
            av.VALUE_SHORT_DESC AS MEDICATION_CLASSIFICATION_CODE_DESC,
            m.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(TO_VARCHAR(m.MEDICATION_CLASSIFICATION_CODE), ''''),
                COALESCE(av.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(m.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_MEDICATIONS m
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av ON m.MEDICATION_CLASSIFICATION_CODE = av.AV_ID
        WHERE m.MEDICATION_CLASSIFICATION_CODE IS NOT NULL;

        UPDATE DCF_RAWDATA.DWH.DIM_MEDICATIONS_INFO tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_MEDICATIONS src
        WHERE tgt.MEDICATION_CLASSIFICATION_CODE_AV_ID = src.MEDICATION_CLASSIFICATION_CODE_AV_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        INSERT INTO DCF_RAWDATA.DWH.DIM_MEDICATIONS_INFO
        (MEDICATION_CLASSIFICATION_CODE_AV_ID, MEDICATION_CLASSIFICATION_CODE_DESC, CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM)
        SELECT src.MEDICATION_CLASSIFICATION_CODE_AV_ID, src.MEDICATION_CLASSIFICATION_CODE_DESC,
               CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_MEDICATIONS src
        WHERE NOT EXISTS (SELECT 1 FROM DCF_RAWDATA.DWH.DIM_MEDICATIONS_INFO tgt
            WHERE tgt.MEDICATION_CLASSIFICATION_CODE_AV_ID = src.MEDICATION_CLASSIFICATION_CODE_AV_ID
              AND tgt.CHECKSUM = src.CHECKSUM AND tgt.UPDATED_DATE IS NULL);

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_MEDICATIONS_INFO load completed. Rows Loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_MEDICATIONS_INFO load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_MEDICATION_HEALTH_BEHAVIOR_INFO"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_MEDICATION_HEALTH_BEHAVIOR_INFO_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_MHB_INFO AS
        SELECT DISTINCT
            mhb.PRESCRIBED_FREQUENCY_CODE AS PRESCRIBED_FREQUENCY_CODE_AV_ID,
            av1.VALUE_SHORT_DESC AS PRESCRIBED_FREQUENCY_CODE_DESC,
            mhb.ADMINISTER_METHOD_CODE AS ADMINISTER_METHOD_CODE_AV_ID,
            av2.VALUE_SHORT_DESC AS ADMINISTER_METHOD_CODE_DESC,
            mhb.CONSENT_DECISION_CODE AS CONSENT_DECISION_CODE_AV_ID,
            av3.VALUE_SHORT_DESC AS CONSENT_DECISION_CODE_DESC,
            mhb.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(mhb.PRESCRIBED_FREQUENCY_CODE, ''''), COALESCE(av1.VALUE_SHORT_DESC, ''''),
                COALESCE(mhb.ADMINISTER_METHOD_CODE, ''''), COALESCE(av2.VALUE_SHORT_DESC, ''''),
                COALESCE(mhb.CONSENT_DECISION_CODE, ''''), COALESCE(av3.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(mhb.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_MEDICATION_HEALTH_BEHAVIOR mhb
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av1 ON mhb.PRESCRIBED_FREQUENCY_CODE = av1.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av2 ON mhb.ADMINISTER_METHOD_CODE = av2.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av3 ON mhb.CONSENT_DECISION_CODE = av3.AV_ID;

        UPDATE DCF_RAWDATA.DWH.DIM_MEDICATION_HEALTH_BEHAVIOR_INFO tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_MHB_INFO src
        WHERE tgt.PRESCRIBED_FREQUENCY_CODE_AV_ID IS NOT DISTINCT FROM src.PRESCRIBED_FREQUENCY_CODE_AV_ID
          AND tgt.ADMINISTER_METHOD_CODE_AV_ID IS NOT DISTINCT FROM src.ADMINISTER_METHOD_CODE_AV_ID
          AND tgt.CONSENT_DECISION_CODE_AV_ID IS NOT DISTINCT FROM src.CONSENT_DECISION_CODE_AV_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        INSERT INTO DCF_RAWDATA.DWH.DIM_MEDICATION_HEALTH_BEHAVIOR_INFO
        (PRESCRIBED_FREQUENCY_CODE_AV_ID, PRESCRIBED_FREQUENCY_CODE_DESC, ADMINISTER_METHOD_CODE_AV_ID, ADMINISTER_METHOD_CODE_DESC,
         CONSENT_DECISION_CODE_AV_ID, CONSENT_DECISION_CODE_DESC, CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM)
        SELECT src.PRESCRIBED_FREQUENCY_CODE_AV_ID, src.PRESCRIBED_FREQUENCY_CODE_DESC,
               src.ADMINISTER_METHOD_CODE_AV_ID, src.ADMINISTER_METHOD_CODE_DESC,
               src.CONSENT_DECISION_CODE_AV_ID, src.CONSENT_DECISION_CODE_DESC,
               CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_MHB_INFO src
        WHERE NOT EXISTS (SELECT 1 FROM DCF_RAWDATA.DWH.DIM_MEDICATION_HEALTH_BEHAVIOR_INFO tgt
            WHERE tgt.PRESCRIBED_FREQUENCY_CODE_AV_ID IS NOT DISTINCT FROM src.PRESCRIBED_FREQUENCY_CODE_AV_ID
              AND tgt.ADMINISTER_METHOD_CODE_AV_ID IS NOT DISTINCT FROM src.ADMINISTER_METHOD_CODE_AV_ID
              AND tgt.CONSENT_DECISION_CODE_AV_ID IS NOT DISTINCT FROM src.CONSENT_DECISION_CODE_AV_ID
              AND tgt.CHECKSUM = src.CHECKSUM AND tgt.UPDATED_DATE IS NULL);

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_MEDICATION_HEALTH_BEHAVIOR_INFO load completed. Rows Loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_MEDICATION_HEALTH_BEHAVIOR_INFO load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_PERSON_ORG_INVOLVEMENT_INFO"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_PERSON_ORG_INVOLVEMENT_INFO_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_POI_INFO AS
        SELECT DISTINCT
            poi.REASON_CLOSED_CODE AS REASON_CLOSED_CODE_AV_ID,
            av.VALUE_SHORT_DESC AS REASON_CLOSED_CODE_DESC,
            poi.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(TO_VARCHAR(poi.REASON_CLOSED_CODE), ''''),
                COALESCE(av.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(poi.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_PERSON_ORG_INVOLVEMENT poi
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av ON poi.REASON_CLOSED_CODE = av.AV_ID;

        UPDATE DCF_RAWDATA.DWH.DIM_PERSON_ORG_INVOLVEMENT_INFO tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_POI_INFO src
        WHERE tgt.REASON_CLOSED_CODE_AV_ID IS NOT DISTINCT FROM src.REASON_CLOSED_CODE_AV_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        INSERT INTO DCF_RAWDATA.DWH.DIM_PERSON_ORG_INVOLVEMENT_INFO
        (REASON_CLOSED_CODE_AV_ID, REASON_CLOSED_CODE_DESC, CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM)
        SELECT src.REASON_CLOSED_CODE_AV_ID, src.REASON_CLOSED_CODE_DESC,
               CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_POI_INFO src
        WHERE NOT EXISTS (SELECT 1 FROM DCF_RAWDATA.DWH.DIM_PERSON_ORG_INVOLVEMENT_INFO tgt
            WHERE tgt.REASON_CLOSED_CODE_AV_ID IS NOT DISTINCT FROM src.REASON_CLOSED_CODE_AV_ID
              AND tgt.CHECKSUM = src.CHECKSUM AND tgt.UPDATED_DATE IS NULL);

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_PERSON_ORG_INVOLVEMENT_INFO load completed. Rows Loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_PERSON_ORG_INVOLVEMENT_INFO load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_PERSON_ROLE_ASSIGNMENTS_INFO"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_PERSON_ROLE_ASSIGNMENTS_INFO_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_PRA_INFO AS
        SELECT DISTINCT
            pra.ROLE_TYPE AS ROLE_TYPE_AV_ID,
            av1.VALUE_SHORT_DESC AS ROLE_TYPE_DESC,
            pra.ROLE_SUB_TYPE AS ROLE_SUB_TYPE_AV_ID,
            av2.VALUE_SHORT_DESC AS ROLE_SUB_TYPE_DESC,
            pra.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(pra.ROLE_TYPE, ''''),
                COALESCE(av1.VALUE_SHORT_DESC, ''''),
                COALESCE(pra.ROLE_SUB_TYPE, ''''),
                COALESCE(av2.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(pra.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_PERSON_ROLE_ASSIGNMENTS pra
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av1 ON pra.ROLE_TYPE = av1.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av2 ON pra.ROLE_SUB_TYPE = av2.AV_ID;

        UPDATE DCF_RAWDATA.DWH.DIM_PERSON_ROLE_ASSIGNMENTS_INFO tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_PRA_INFO src
        WHERE tgt.ROLE_TYPE_AV_ID IS NOT DISTINCT FROM src.ROLE_TYPE_AV_ID
          AND tgt.ROLE_SUB_TYPE_AV_ID IS NOT DISTINCT FROM src.ROLE_SUB_TYPE_AV_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        INSERT INTO DCF_RAWDATA.DWH.DIM_PERSON_ROLE_ASSIGNMENTS_INFO
        (ROLE_TYPE_AV_ID, ROLE_TYPE_DESC, ROLE_SUB_TYPE_AV_ID, ROLE_SUB_TYPE_DESC, CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM)
        SELECT src.ROLE_TYPE_AV_ID, src.ROLE_TYPE_DESC, src.ROLE_SUB_TYPE_AV_ID, src.ROLE_SUB_TYPE_DESC,
               CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_PRA_INFO src
        WHERE NOT EXISTS (SELECT 1 FROM DCF_RAWDATA.DWH.DIM_PERSON_ROLE_ASSIGNMENTS_INFO tgt
            WHERE tgt.ROLE_TYPE_AV_ID IS NOT DISTINCT FROM src.ROLE_TYPE_AV_ID
              AND tgt.ROLE_SUB_TYPE_AV_ID IS NOT DISTINCT FROM src.ROLE_SUB_TYPE_AV_ID
              AND tgt.CHECKSUM = src.CHECKSUM AND tgt.UPDATED_DATE IS NULL);

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_PERSON_ROLE_ASSIGNMENTS_INFO load completed. Rows Loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_PERSON_ROLE_ASSIGNMENTS_INFO load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_DIM_T_PERSONS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_DIM_T_PERSONS_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;
    LET rows_failed INTEGER := 0;
    LET run_status STRING := ''SUCCESS'';

    BEGIN
        CREATE OR REPLACE TEMP TABLE TEMP_T_PERSONS AS
        SELECT DISTINCT
            p.PERSON_ID,
            p.LAST_NAME,
            CONCAT(COALESCE(p.FIRST_NAME, ''''), '' '', COALESCE(p.LAST_NAME, '''')) AS FULL_NAME,
            p.CITIZENSHIP_CODE AS CITIZENSHIP_CODE_AV_ID,
            av1.VALUE_SHORT_DESC AS CITIZENSHIP_CODE_DESC,
            p.PRIMARY_LANGUAGE_CODE AS PRIMARY_LANGUAGE_CODE_AV_ID,
            av2.VALUE_SHORT_DESC AS PRIMARY_LANGUAGE_CODE_DESC,
            p.DO_NOT_RESUSCITATE_IND, p.EDUCATIONAL_PARENT_IND, p.GUARDIANSHIP_CONSENT_IND,
            p.ADOPTION_NOT_APPROPRIATE_IND, p.BIO_PARENTS_RETURN_IND, p.BIRTH_CERTIFICATE_AVLBL_IND,
            p.NO_PHONE_IND, p.PET_OWNER_IND, p.SMOKER_IND, p.SSN_VALIDATION_IND, p.RESTRICTED_IND,
            p.ADOPTION_MATCH_FOUND_IND,
            p.MARITAL_STATUS_CODE AS MARITAL_STATUS_CODE_AV_ID, av3.VALUE_SHORT_DESC AS MARITAL_STATUS_CODE_DESC,
            p.PREFIX_CODE AS PREFIX_CODE_AV_ID, av4.VALUE_SHORT_DESC AS PREFIX_CODE_DESC,
            p.FIRST_NAME, p.MIDDLE_NAME,
            p.SUFFIX_CODE AS SUFFIX_CODE_AV_ID, av5.VALUE_SHORT_DESC AS SUFFIX_CODE_DESC,
            p.PROFESSIONAL_SUFFIX_CODE AS PROFESSIONAL_SUFFIX_CODE_AV_ID, av6.VALUE_SHORT_DESC AS PROFESSIONAL_SUFFIX_CODE_DESC,
            p.AGE_NUM, p.AGE_UNIT_CODE AS AGE_UNIT_CODE_AV_ID, av7.VALUE_SHORT_DESC AS AGE_UNIT_CODE_DESC,
            p.BIRTH_DATE, DATEDIFF(''YEAR'', p.BIRTH_DATE, CURRENT_DATE()) AS CURRENT_AGE,
            p.BIRTH_PLACE_STATE_CODE AS BIRTH_PLACE_STATE_CODE_AV_ID, av8.VALUE_SHORT_DESC AS BIRTH_PLACE_STATE_DESC,
            p.BIRTH_PLACE_CITY_NAME, p.BIRTH_PLACE_HOSPITAL_NAME,
            p.BIRTH_PLACE_COUNTRY_CODE AS BIRTH_PLACE_COUNTRY_CODE_AV_ID, av9.VALUE_SHORT_DESC AS BIRTH_PLACE_COUNTRY_CODE_DESC,
            p.DECEASED_DATE,
            p.DECEASED_COUNTRY_CODE AS DECEASED_COUNTRY_CODE_AV_ID, av10.VALUE_SHORT_DESC AS DECEASED_COUNTRY_CODE_DESC,
            p.DECEASED_CITY_NAME,
            p.DECEASED_STATE_CODE AS DECEASED_STATE_CODE_AV_ID, av11.VALUE_SHORT_DESC AS DECEASED_STATE_CODE_DESC,
            p.ALIEN_REGISTRATION_NUM,
            p.CURRENT_GRADE_CODE AS CURRENT_GRADE_CODE_AV_ID, av12.VALUE_SHORT_DESC AS CURRENT_GRADE_CODE_DESC,
            p.ETHNICITY_CODE AS ETHNICITY_CODE_AV_ID, av13.VALUE_SHORT_DESC AS ETHNICITY_CODE_DESC,
            p.GENDER_CODE AS GENDER_CODE_AV_ID, av14.VALUE_SHORT_DESC AS GENDER_CODE_DESC,
            p.IMMIGRATION_STATUS_CODE AS IMMIGRATION_STATUS_CODE_AV_ID, av15.VALUE_SHORT_DESC AS IMMIGRATION_STATUS_CODE_DESC,
            p.OCCUPATION_DESC,
            p.RACE_CODE AS RACE_CODE_AV_ID, av16.VALUE_SHORT_DESC AS RACE_CODE_DESC,
            p.RELIGION_CODE AS RELIGION_CODE_AV_ID, av17.VALUE_SHORT_DESC AS RELIGION_CODE_DESC,
            p.SOCIAL_SECURITY_NUM,
            p.SSN_SOURCE_CODE AS SSN_SOURCE_CODE_AV_ID, av18.VALUE_SHORT_DESC AS SSN_SOURCE_CODE_DESC,
            p.SSN_REFUSAL_DATE, p.BIRTH_ORDER_SEQUENCE_NUM, p.MARITAL_STATUS_EFFECT_DATE,
            p.COMMON_CLIENT_ID,
            p.CHILD_ADOPTED_CODE AS CHILD_ADOPTED_CODE_AV_ID, av19.VALUE_SHORT_DESC AS CHILD_ADOPTED_CODE_DESC,
            p.AGE_CHILD_ADOPTED_NUM,
            p.AGE_CHILD_ADP_UNIT_CODE AS AGE_CHILD_ADP_UNIT_CODE_AV_ID, av20.VALUE_SHORT_DESC AS AGE_CHILD_ADP_UNIT_CODE_DESC,
            p.GESTATIONAL_AGE_NUM, p.US_ENTRY_DATE, p.ADOPTION_FREED_DATE,
            p.ARCHIVE_DATE, p.ARCHIVE_FILE_NAME, p.LAST_ELECTRON_RETRIEVAL_DATE,
            p.PERSON_PERSON_REQUESTS_ID, p.AFCARS_ADOPTION_SEND_DATE,
            p.DUP_PERSON_STATUS_CODE AS DUP_PERSON_STATUS_CODE_AV_ID, av21.VALUE_SHORT_DESC AS DUP_PERSON_STATUS_CODE_DESC,
            p.PERSON_PERSON_PRIMARY_ID,
            p.APPROXIMATE_DOB_IND, p.CHILD_ADOPTED_DATE, p.APPROX_LAST_ADOPTED_DATE_IND,
            p.ITIN_NUM,
            p.ADD_TS, p.ADD_USER, p.MOD_TS, p.MOD_USER, p.DELETED_DATE,
            SHA2(CONCAT_WS(''|'',
                COALESCE(TO_VARCHAR(p.PERSON_ID), ''''),
                COALESCE(p.LAST_NAME, ''''), COALESCE(p.FIRST_NAME, ''''),
                COALESCE(TO_VARCHAR(p.CITIZENSHIP_CODE), ''''), COALESCE(av1.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(p.PRIMARY_LANGUAGE_CODE), ''''), COALESCE(av2.VALUE_SHORT_DESC, ''''),
                COALESCE(p.DO_NOT_RESUSCITATE_IND, ''''), COALESCE(p.EDUCATIONAL_PARENT_IND, ''''),
                COALESCE(TO_VARCHAR(p.GENDER_CODE), ''''), COALESCE(av14.VALUE_SHORT_DESC, ''''),
                COALESCE(TO_VARCHAR(p.BIRTH_DATE), ''''),
                COALESCE(p.ADD_USER, ''''), COALESCE(TO_VARCHAR(p.ADD_TS), ''''),
                COALESCE(p.MOD_USER, ''''), COALESCE(TO_VARCHAR(p.MOD_TS), ''''),
                COALESCE(TO_VARCHAR(p.DELETED_DATE), '''')
            )) AS CHECKSUM
        FROM DCF_RAWDATA.STAGING.STG_PERSONS p
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av1 ON p.CITIZENSHIP_CODE = av1.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av2 ON p.PRIMARY_LANGUAGE_CODE = av2.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av3 ON p.MARITAL_STATUS_CODE = av3.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av4 ON p.PREFIX_CODE = av4.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av5 ON p.SUFFIX_CODE = av5.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av6 ON p.PROFESSIONAL_SUFFIX_CODE = av6.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av7 ON p.AGE_UNIT_CODE = av7.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av8 ON p.BIRTH_PLACE_STATE_CODE = av8.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av9 ON p.BIRTH_PLACE_COUNTRY_CODE = av9.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av10 ON p.DECEASED_COUNTRY_CODE = av10.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av11 ON p.DECEASED_STATE_CODE = av11.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av12 ON p.CURRENT_GRADE_CODE = av12.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av13 ON p.ETHNICITY_CODE = av13.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av14 ON p.GENDER_CODE = av14.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av15 ON p.IMMIGRATION_STATUS_CODE = av15.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av16 ON p.RACE_CODE = av16.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av17 ON p.RELIGION_CODE = av17.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av18 ON p.SSN_SOURCE_CODE = av18.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av19 ON p.CHILD_ADOPTED_CODE = av19.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av20 ON p.AGE_CHILD_ADP_UNIT_CODE = av20.AV_ID
        LEFT JOIN DCF_RAWDATA.STAGING.STG_ALLOWABLE_VALUES av21 ON p.DUP_PERSON_STATUS_CODE = av21.AV_ID;

        -- SCD2: Close existing records where checksum changed
        UPDATE DCF_RAWDATA.DWH.DIM_T_PERSONS tgt
        SET UPDATED_DATE = CURRENT_TIMESTAMP()
        FROM TEMP_T_PERSONS src
        WHERE tgt.PERSON_ID = src.PERSON_ID
          AND tgt.UPDATED_DATE IS NULL
          AND tgt.CHECKSUM <> src.CHECKSUM;

        -- SCD2: Insert new version
        INSERT INTO DCF_RAWDATA.DWH.DIM_T_PERSONS
        (
            PERSON_ID, LAST_NAME, FULL_NAME,
            CITIZENSHIP_CODE_AV_ID, CITIZENSHIP_CODE_DESC,
            PRIMARY_LANGUAGE_CODE_AV_ID, PRIMARY_LANGUAGE_CODE_DESC,
            DO_NOT_RESUSCITATE_IND, EDUCATIONAL_PARENT_IND, GUARDIANSHIP_CONSENT_IND,
            ADOPTION_NOT_APPROPRIATE_IND, BIO_PARENTS_RETURN_IND, BIRTH_CERTIFICATE_AVLBL_IND,
            NO_PHONE_IND, PET_OWNER_IND, SMOKER_IND, SSN_VALIDATION_IND, RESTRICTED_IND,
            ADOPTION_MATCH_FOUND_IND,
            MARITAL_STATUS_CODE_AV_ID, MARITAL_STATUS_CODE_DESC,
            PREFIX_CODE_AV_ID, PREFIX_CODE_DESC,
            FIRST_NAME, MIDDLE_NAME,
            SUFFIX_CODE_AV_ID, SUFFIX_CODE_DESC,
            PROFESSIONAL_SUFFIX_CODE_AV_ID, PROFESSIONAL_SUFFIX_CODE_DESC,
            AGE_NUM, AGE_UNIT_CODE_AV_ID, AGE_UNIT_CODE_DESC,
            BIRTH_DATE, CURRENT_AGE,
            BIRTH_PLACE_STATE_CODE_AV_ID, BIRTH_PLACE_STATE_DESC,
            BIRTH_PLACE_CITY_NAME, BIRTH_PLACE_HOSPITAL_NAME,
            BIRTH_PLACE_COUNTRY_CODE_AV_ID, BIRTH_PLACE_COUNTRY_CODE_DESC,
            DECEASED_DATE,
            DECEASED_COUNTRY_CODE_AV_ID, DECEASED_COUNTRY_CODE_DESC,
            DECEASED_CITY_NAME,
            DECEASED_STATE_CODE_AV_ID, DECEASED_STATE_CODE_DESC,
            ALIEN_REGISTRATION_NUM,
            CURRENT_GRADE_CODE_AV_ID, CURRENT_GRADE_CODE_DESC,
            ETHNICITY_CODE_AV_ID, ETHNICITY_CODE_DESC,
            GENDER_CODE_AV_ID, GENDER_CODE_DESC,
            IMMIGRATION_STATUS_CODE_AV_ID, IMMIGRATION_STATUS_CODE_DESC,
            OCCUPATION_DESC,
            RACE_CODE_AV_ID, RACE_CODE_DESC,
            RELIGION_CODE_AV_ID, RELIGION_CODE_DESC,
            SOCIAL_SECURITY_NUM,
            SSN_SOURCE_CODE_AV_ID, SSN_SOURCE_CODE_DESC,
            SSN_REFUSAL_DATE, BIRTH_ORDER_SEQUENCE_NUM, MARITAL_STATUS_EFFECT_DATE,
            COMMON_CLIENT_ID,
            CHILD_ADOPTED_CODE_AV_ID, CHILD_ADOPTED_CODE_DESC,
            AGE_CHILD_ADOPTED_NUM,
            AGE_CHILD_ADP_UNIT_CODE_AV_ID, AGE_CHILD_ADP_UNIT_CODE_DESC,
            GESTATIONAL_AGE_NUM, US_ENTRY_DATE, ADOPTION_FREED_DATE,
            ARCHIVE_DATE, ARCHIVE_FILE_NAME, LAST_ELECTRON_RETRIEVAL_DATE,
            PERSON_PERSON_REQUESTS_ID, AFCARS_ADOPTION_SEND_DATE,
            DUP_PERSON_STATUS_CODE_AV_ID, DUP_PERSON_STATUS_CODE_DESC,
            PERSON_PERSON_PRIMARY_ID,
            APPROXIMATE_DOB_IND, CHILD_ADOPTED_DATE, APPROX_LAST_ADOPTED_DATE_IND,
            ITIN_NUM,
            ADD_TS, ADD_USER, MOD_TS, MOD_USER,
            CREATED_DATE, UPDATED_DATE, DELETED_DATE, CHECKSUM
        )
        SELECT
            src.PERSON_ID, src.LAST_NAME, src.FULL_NAME,
            src.CITIZENSHIP_CODE_AV_ID, src.CITIZENSHIP_CODE_DESC,
            src.PRIMARY_LANGUAGE_CODE_AV_ID, src.PRIMARY_LANGUAGE_CODE_DESC,
            src.DO_NOT_RESUSCITATE_IND, src.EDUCATIONAL_PARENT_IND, src.GUARDIANSHIP_CONSENT_IND,
            src.ADOPTION_NOT_APPROPRIATE_IND, src.BIO_PARENTS_RETURN_IND, src.BIRTH_CERTIFICATE_AVLBL_IND,
            src.NO_PHONE_IND, src.PET_OWNER_IND, src.SMOKER_IND, src.SSN_VALIDATION_IND, src.RESTRICTED_IND,
            src.ADOPTION_MATCH_FOUND_IND,
            src.MARITAL_STATUS_CODE_AV_ID, src.MARITAL_STATUS_CODE_DESC,
            src.PREFIX_CODE_AV_ID, src.PREFIX_CODE_DESC,
            src.FIRST_NAME, src.MIDDLE_NAME,
            src.SUFFIX_CODE_AV_ID, src.SUFFIX_CODE_DESC,
            src.PROFESSIONAL_SUFFIX_CODE_AV_ID, src.PROFESSIONAL_SUFFIX_CODE_DESC,
            src.AGE_NUM, src.AGE_UNIT_CODE_AV_ID, src.AGE_UNIT_CODE_DESC,
            src.BIRTH_DATE, src.CURRENT_AGE,
            src.BIRTH_PLACE_STATE_CODE_AV_ID, src.BIRTH_PLACE_STATE_DESC,
            src.BIRTH_PLACE_CITY_NAME, src.BIRTH_PLACE_HOSPITAL_NAME,
            src.BIRTH_PLACE_COUNTRY_CODE_AV_ID, src.BIRTH_PLACE_COUNTRY_CODE_DESC,
            src.DECEASED_DATE,
            src.DECEASED_COUNTRY_CODE_AV_ID, src.DECEASED_COUNTRY_CODE_DESC,
            src.DECEASED_CITY_NAME,
            src.DECEASED_STATE_CODE_AV_ID, src.DECEASED_STATE_CODE_DESC,
            src.ALIEN_REGISTRATION_NUM,
            src.CURRENT_GRADE_CODE_AV_ID, src.CURRENT_GRADE_CODE_DESC,
            src.ETHNICITY_CODE_AV_ID, src.ETHNICITY_CODE_DESC,
            src.GENDER_CODE_AV_ID, src.GENDER_CODE_DESC,
            src.IMMIGRATION_STATUS_CODE_AV_ID, src.IMMIGRATION_STATUS_CODE_DESC,
            src.OCCUPATION_DESC,
            src.RACE_CODE_AV_ID, src.RACE_CODE_DESC,
            src.RELIGION_CODE_AV_ID, src.RELIGION_CODE_DESC,
            src.SOCIAL_SECURITY_NUM,
            src.SSN_SOURCE_CODE_AV_ID, src.SSN_SOURCE_CODE_DESC,
            src.SSN_REFUSAL_DATE, src.BIRTH_ORDER_SEQUENCE_NUM, src.MARITAL_STATUS_EFFECT_DATE,
            src.COMMON_CLIENT_ID,
            src.CHILD_ADOPTED_CODE_AV_ID, src.CHILD_ADOPTED_CODE_DESC,
            src.AGE_CHILD_ADOPTED_NUM,
            src.AGE_CHILD_ADP_UNIT_CODE_AV_ID, src.AGE_CHILD_ADP_UNIT_CODE_DESC,
            src.GESTATIONAL_AGE_NUM, src.US_ENTRY_DATE, src.ADOPTION_FREED_DATE,
            src.ARCHIVE_DATE, src.ARCHIVE_FILE_NAME, src.LAST_ELECTRON_RETRIEVAL_DATE,
            src.PERSON_PERSON_REQUESTS_ID, src.AFCARS_ADOPTION_SEND_DATE,
            src.DUP_PERSON_STATUS_CODE_AV_ID, src.DUP_PERSON_STATUS_CODE_DESC,
            src.PERSON_PERSON_PRIMARY_ID,
            src.APPROXIMATE_DOB_IND, src.CHILD_ADOPTED_DATE, src.APPROX_LAST_ADOPTED_DATE_IND,
            src.ITIN_NUM,
            src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER,
            CURRENT_TIMESTAMP(), NULL, src.DELETED_DATE, src.CHECKSUM
        FROM TEMP_T_PERSONS src
        WHERE NOT EXISTS (
            SELECT 1 FROM DCF_RAWDATA.DWH.DIM_T_PERSONS tgt
            WHERE tgt.PERSON_ID = src.PERSON_ID
              AND tgt.CHECKSUM = src.CHECKSUM
              AND tgt.UPDATED_DATE IS NULL
        );

        rows_loaded := (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''DIM_T_PERSONS load completed. Rows Loaded: '' || :rows_loaded);

        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''DIM_T_PERSONS load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_FACT_CASES"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_FACT_CASES_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        MERGE INTO DCF_RAWDATA.DWH.FACT_CASES tgt
        USING (
            SELECT
                c.CAS_ID, c.CASE_NAME, d.CASES_INFO_ID,
                c.RESTRICTED_IND, c.CASE_ACCESS_IND,
                TRY_TO_NUMBER(c.ASSIST_CASE_NUM) AS ASSIST_CAS_NUM,
                c.EXPECTED_CLOSE_DATE, c.UNIT_ORGN_ID, c.AREA_ORGN_ID, c.REGION_ORGN_ID,
                c.CURRENT_CASE_STATUS_DATE, c.RESTRICTION_DATE,
                c.ADD_TS, c.ADD_USER, c.MOD_TS, c.MOD_USER,
                CURRENT_TIMESTAMP() AS CREATED_DATE, c.DELETED_DATE,
                MD5(CONCAT_WS(''|'',
                    COALESCE(c.CASE_NAME, ''''), COALESCE(TO_VARCHAR(d.CASES_INFO_ID), ''''),
                    COALESCE(c.RESTRICTED_IND, ''''), COALESCE(c.CASE_ACCESS_IND, ''''),
                    COALESCE(TO_VARCHAR(TRY_TO_NUMBER(c.ASSIST_CASE_NUM)), ''''),
                    COALESCE(TO_VARCHAR(c.EXPECTED_CLOSE_DATE), ''''),
                    COALESCE(TO_VARCHAR(c.UNIT_ORGN_ID), ''''), COALESCE(TO_VARCHAR(c.AREA_ORGN_ID), ''''),
                    COALESCE(TO_VARCHAR(c.REGION_ORGN_ID), ''''),
                    COALESCE(TO_VARCHAR(c.CURRENT_CASE_STATUS_DATE), ''''),
                    COALESCE(TO_VARCHAR(c.RESTRICTION_DATE), ''''),
                    COALESCE(TO_VARCHAR(c.ADD_TS), ''''), COALESCE(c.ADD_USER, ''''),
                    COALESCE(TO_VARCHAR(c.MOD_TS), ''''), COALESCE(c.MOD_USER, ''''),
                    COALESCE(TO_VARCHAR(c.DELETED_DATE), '''')
                )) AS CHECKSUM
            FROM DCF_RAWDATA.STAGING.STG_CASES c
            INNER JOIN DCF_RAWDATA.DWH.DIM_CASES_INFO d
                ON c.CASE_TYPE IS NOT DISTINCT FROM d.CASE_TYPE_AV_ID
               AND c.CURRENT_CASE_STATUS_CODE IS NOT DISTINCT FROM d.CURRENT_CASE_STATUS_CODE_AV_ID
               AND c.RESTRICTION_REASON_CODE IS NOT DISTINCT FROM d.RESTRICTION_REASON_CODE_AV_ID
               AND d.UPDATED_DATE IS NULL
        ) src ON tgt.CAS_ID = src.CAS_ID
        WHEN MATCHED AND src.CHECKSUM <> tgt.CHECKSUM THEN
            UPDATE SET
                CASE_NAME=src.CASE_NAME, CASES_INFO_ID=src.CASES_INFO_ID,
                RESTRICTED_IND=src.RESTRICTED_IND, CASE_ACCESS_IND=src.CASE_ACCESS_IND,
                ASSIST_CAS_NUM=src.ASSIST_CAS_NUM, EXPECTED_CLOSE_DATE=src.EXPECTED_CLOSE_DATE,
                UNIT_ORGN_ID=src.UNIT_ORGN_ID, AREA_ORGN_ID=src.AREA_ORGN_ID, REGION_ORGN_ID=src.REGION_ORGN_ID,
                CURRENT_CASE_STATUS_DATE=src.CURRENT_CASE_STATUS_DATE, RESTRICTION_DATE=src.RESTRICTION_DATE,
                ADD_TS=src.ADD_TS, ADD_USER=src.ADD_USER, MOD_TS=src.MOD_TS, MOD_USER=src.MOD_USER,
                DELETED_DATE=src.DELETED_DATE, CHECKSUM=src.CHECKSUM
        WHEN NOT MATCHED THEN
            INSERT (CAS_ID, CASE_NAME, CASES_INFO_ID, RESTRICTED_IND, CASE_ACCESS_IND, ASSIST_CAS_NUM,
                    EXPECTED_CLOSE_DATE, UNIT_ORGN_ID, AREA_ORGN_ID, REGION_ORGN_ID,
                    CURRENT_CASE_STATUS_DATE, RESTRICTION_DATE, ADD_TS, ADD_USER, MOD_TS, MOD_USER,
                    CREATED_DATE, DELETED_DATE, CHECKSUM)
            VALUES (src.CAS_ID, src.CASE_NAME, src.CASES_INFO_ID, src.RESTRICTED_IND, src.CASE_ACCESS_IND, src.ASSIST_CAS_NUM,
                    src.EXPECTED_CLOSE_DATE, src.UNIT_ORGN_ID, src.AREA_ORGN_ID, src.REGION_ORGN_ID,
                    src.CURRENT_CASE_STATUS_DATE, src.RESTRICTION_DATE, src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER,
                    src.CREATED_DATE, src.DELETED_DATE, src.CHECKSUM);

        rows_loaded := (SELECT $1 + $2 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''FACT_CASES load completed. Rows loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''FACT_CASES load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_FACT_CUSTODIES"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_FACT_CUSTODIES_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        MERGE INTO DCF_RAWDATA.DWH.FACT_CUSTODIES tgt
        USING (
            SELECT c.CUS_ID, d.CUSTODIES_INFO_ID, c.TWENTY_NINE_C_IND, c.START_DATE,
                   c.PERSON_PERSON_ID, c.ORGN_ORGN_ID, c.VPA_VPA_ID, c.SUR_SUR_ID,
                   c.CAP_CAP_ID, c.POI_POI_ID, c.CHILD_ADJUDICATED_DATE, c.END_DATE,
                   c.TWENTY_NINE_C_DATE, c.REASONABLE_EFFORT_DATE, c.PERSON_PERSON_CHILD_ID,
                   c.MOD_CAP_CAP_ID, c.ADD_TS, c.ADD_USER, c.MOD_TS, c.MOD_USER,
                   CURRENT_TIMESTAMP() AS CREATED_DATE, c.DELETED_DATE, c.CHECKSUM
            FROM DCF_RAWDATA.STAGING.STG_CUSTODIES c
            LEFT JOIN DCF_RAWDATA.DWH.DIM_CUSTODIES_INFO d
                ON c.LEGAL_STATUS_CODE IS NOT DISTINCT FROM d.LEGAL_STATUS_CODE_AV_ID
               AND c.END_REASON_CODE IS NOT DISTINCT FROM d.END_REASON_CODE_AV_ID
               AND c.CUSTODY_TYPE IS NOT DISTINCT FROM d.CUSTODY_TYPE_AV_ID
               AND d.UPDATED_DATE IS NULL
        ) src ON tgt.CUS_ID = src.CUS_ID
        WHEN MATCHED AND src.CHECKSUM <> tgt.CHECKSUM THEN
            UPDATE SET
                CUSTODIES_INFO_ID=src.CUSTODIES_INFO_ID, TWENTY_NINE_C_IND=src.TWENTY_NINE_C_IND,
                START_DATE=src.START_DATE, PERSON_PERSON_ID=src.PERSON_PERSON_ID,
                ORGN_ORGN_ID=src.ORGN_ORGN_ID, VPA_VPA_ID=src.VPA_VPA_ID, SUR_SUR_ID=src.SUR_SUR_ID,
                CAP_CAP_ID=src.CAP_CAP_ID, POI_POI_ID=src.POI_POI_ID,
                CHILD_ADJUDICATED_DATE=src.CHILD_ADJUDICATED_DATE, END_DATE=src.END_DATE,
                TWENTY_NINE_C_DATE=src.TWENTY_NINE_C_DATE, REASONABLE_EFFORT_DATE=src.REASONABLE_EFFORT_DATE,
                PERSON_PERSON_CHILD_ID=src.PERSON_PERSON_CHILD_ID, MOD_CAP_CAP_ID=src.MOD_CAP_CAP_ID,
                ADD_TS=src.ADD_TS, ADD_USER=src.ADD_USER, MOD_TS=src.MOD_TS, MOD_USER=src.MOD_USER,
                DELETED_DATE=src.DELETED_DATE, CHECKSUM=src.CHECKSUM
        WHEN NOT MATCHED THEN
            INSERT (CUS_ID, CUSTODIES_INFO_ID, TWENTY_NINE_C_IND, START_DATE, PERSON_PERSON_ID, ORGN_ORGN_ID,
                    VPA_VPA_ID, SUR_SUR_ID, CAP_CAP_ID, POI_POI_ID, CHILD_ADJUDICATED_DATE, END_DATE,
                    TWENTY_NINE_C_DATE, REASONABLE_EFFORT_DATE, PERSON_PERSON_CHILD_ID, MOD_CAP_CAP_ID,
                    ADD_TS, ADD_USER, MOD_TS, MOD_USER, CREATED_DATE, DELETED_DATE, CHECKSUM)
            VALUES (src.CUS_ID, src.CUSTODIES_INFO_ID, src.TWENTY_NINE_C_IND, src.START_DATE, src.PERSON_PERSON_ID, src.ORGN_ORGN_ID,
                    src.VPA_VPA_ID, src.SUR_SUR_ID, src.CAP_CAP_ID, src.POI_POI_ID, src.CHILD_ADJUDICATED_DATE, src.END_DATE,
                    src.TWENTY_NINE_C_DATE, src.REASONABLE_EFFORT_DATE, src.PERSON_PERSON_CHILD_ID, src.MOD_CAP_CAP_ID,
                    src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER, src.CREATED_DATE, src.DELETED_DATE, src.CHECKSUM);

        rows_loaded := (SELECT $1 + $2 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''FACT_CUSTODIES load completed. Rows loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''FACT_CUSTODIES load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_FACT_MEDICATIONS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_FACT_MEDICATIONS_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        MERGE INTO DCF_RAWDATA.DWH.FACT_MEDICATIONS tgt
        USING (
            SELECT m.MED_ID, d.MEDICATIONS_INFO_ID, m.COMMON_NAME, m.ROGER_DECISION_DRUG_IND,
                   m.MEDICATION_DESC, m.ALLOW_FREQUENCY_NUM, m.ADD_PERSON_ID, m.ADD_ORGN_ID,
                   m.MOD_PERSON_ID, m.MOD_ORGN_ID, m.ADD_TS, m.ADD_USER, m.MOD_TS, m.MOD_USER,
                   CURRENT_TIMESTAMP() AS CREATED_DATE, m.DELETED_DATE
            FROM DCF_RAWDATA.STAGING.STG_MEDICATIONS m
            INNER JOIN DCF_RAWDATA.DWH.DIM_MEDICATIONS_INFO d
                ON m.MEDICATION_CLASSIFICATION_CODE = d.MEDICATION_CLASSIFICATION_CODE_AV_ID
               AND d.UPDATED_DATE IS NULL
        ) src ON tgt.MED_ID = src.MED_ID
        WHEN MATCHED AND (src.MOD_TS > tgt.MOD_TS OR (tgt.MOD_TS IS NULL AND src.MOD_TS IS NOT NULL) OR src.ADD_TS > tgt.ADD_TS) THEN
            UPDATE SET
                MEDICATIONS_INFO_ID=src.MEDICATIONS_INFO_ID, COMMON_NAME=src.COMMON_NAME,
                ROGER_DECISION_DRUG_IND=src.ROGER_DECISION_DRUG_IND, MEDICATION_DESC=src.MEDICATION_DESC,
                ALLOW_FREQUENCY_NUM=src.ALLOW_FREQUENCY_NUM, ADD_PERSON_ID=src.ADD_PERSON_ID,
                ADD_ORGN_ID=src.ADD_ORGN_ID, MOD_PERSON_ID=src.MOD_PERSON_ID, MOD_ORGN_ID=src.MOD_ORGN_ID,
                ADD_TS=src.ADD_TS, ADD_USER=src.ADD_USER, MOD_TS=src.MOD_TS, MOD_USER=src.MOD_USER,
                DELETED_DATE=src.DELETED_DATE
        WHEN NOT MATCHED THEN
            INSERT (MED_ID, MEDICATIONS_INFO_ID, COMMON_NAME, ROGER_DECISION_DRUG_IND, MEDICATION_DESC,
                    ALLOW_FREQUENCY_NUM, ADD_PERSON_ID, ADD_ORGN_ID, MOD_PERSON_ID, MOD_ORGN_ID,
                    ADD_TS, ADD_USER, MOD_TS, MOD_USER, CREATED_DATE, DELETED_DATE)
            VALUES (src.MED_ID, src.MEDICATIONS_INFO_ID, src.COMMON_NAME, src.ROGER_DECISION_DRUG_IND, src.MEDICATION_DESC,
                    src.ALLOW_FREQUENCY_NUM, src.ADD_PERSON_ID, src.ADD_ORGN_ID, src.MOD_PERSON_ID, src.MOD_ORGN_ID,
                    src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER, src.CREATED_DATE, src.DELETED_DATE);

        rows_loaded := (SELECT $1 + $2 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''FACT_MEDICATIONS load completed. Rows loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''FACT_MEDICATIONS load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_FACT_MEDICATION_HEALTH_BEHAVIOR"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_FACT_MEDICATION_HEALTH_BEHAVIOR_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        MERGE INTO DCF_RAWDATA.DWH.FACT_MEDICATION_HEALTH_BEHAVIOR tgt
        USING (
            SELECT mhb.MHP_ID, mhb.MED_MED_ID, mhb.HPP_HPP_ID,
                   mhb.PERSON_PERSON_PATIENT_ID, mhb.PERSON_PERSON_PRESCRIBER_ID,
                   mhb.PRESCRIBER_PCS_PCS_ID, mhb.CONSENT_BY_PERSON_PERSON_ID,
                   d.MEDICATION_HEALTH_BEHAVIOR_INFO_ID,
                   mhb.ADD_PERSON_ID, mhb.ADD_ORGN_ID, mhb.MOD_PERSON_ID, mhb.MOD_ORGN_ID,
                   mhb.THRIVE_FAILURE_IND, mhb.DATE_UNKNOWN,
                   mhb.MEDICATION_CMNT, mhb.DOSAGE_DESC, mhb.CLN_RESP_ADVERSE_EFFECT_CMNT, mhb.CONSENT_COMMENTS,
                   mhb.START_DATE, mhb.END_DATE, mhb.LAST_REFILL_DATE, mhb.CONSENT_DATE,
                   mhb.ADD_TS, mhb.ADD_USER, mhb.MOD_TS, mhb.MOD_USER,
                   CURRENT_TIMESTAMP() AS CREATED_DATE, mhb.DELETED_DATE, mhb.CHECKSUM
            FROM DCF_RAWDATA.STAGING.STG_MEDICATION_HEALTH_BEHAVIOR mhb
            LEFT JOIN DCF_RAWDATA.DWH.DIM_MEDICATION_HEALTH_BEHAVIOR_INFO d
                ON mhb.PRESCRIBED_FREQUENCY_CODE IS NOT DISTINCT FROM d.PRESCRIBED_FREQUENCY_CODE_AV_ID
               AND mhb.ADMINISTER_METHOD_CODE IS NOT DISTINCT FROM d.ADMINISTER_METHOD_CODE_AV_ID
               AND mhb.CONSENT_DECISION_CODE IS NOT DISTINCT FROM d.CONSENT_DECISION_CODE_AV_ID
               AND d.UPDATED_DATE IS NULL
        ) src ON tgt.MHP_ID = src.MHP_ID
        WHEN MATCHED AND src.CHECKSUM <> tgt.CHECKSUM THEN
            UPDATE SET
                MED_MED_ID=src.MED_MED_ID, HPP_HPP_ID=src.HPP_HPP_ID,
                PERSON_PERSON_PATIENT_ID=src.PERSON_PERSON_PATIENT_ID,
                PERSON_PERSON_PRESCRIBER_ID=src.PERSON_PERSON_PRESCRIBER_ID,
                PRESCRIBER_PCS_PCS_ID=src.PRESCRIBER_PCS_PCS_ID,
                CONSENT_BY_PERSON_PERSON_ID=src.CONSENT_BY_PERSON_PERSON_ID,
                MEDICATION_HEALTH_BEHAVIOR_INFO_ID=src.MEDICATION_HEALTH_BEHAVIOR_INFO_ID,
                ADD_PERSON_ID=src.ADD_PERSON_ID, ADD_ORGN_ID=src.ADD_ORGN_ID,
                MOD_PERSON_ID=src.MOD_PERSON_ID, MOD_ORGN_ID=src.MOD_ORGN_ID,
                THRIVE_FAILURE_IND=src.THRIVE_FAILURE_IND, DATE_UNKNOWN=src.DATE_UNKNOWN,
                MEDICATION_CMNT=src.MEDICATION_CMNT, DOSAGE_DESC=src.DOSAGE_DESC,
                CLN_RESP_ADVERSE_EFFECT_CMNT=src.CLN_RESP_ADVERSE_EFFECT_CMNT,
                CONSENT_COMMENTS=src.CONSENT_COMMENTS,
                START_DATE=src.START_DATE, END_DATE=src.END_DATE,
                LAST_REFILL_DATE=src.LAST_REFILL_DATE, CONSENT_DATE=src.CONSENT_DATE,
                ADD_TS=src.ADD_TS, ADD_USER=src.ADD_USER, MOD_TS=src.MOD_TS, MOD_USER=src.MOD_USER,
                DELETED_DATE=src.DELETED_DATE, CHECKSUM=src.CHECKSUM
        WHEN NOT MATCHED THEN
            INSERT (MHP_ID, MED_MED_ID, HPP_HPP_ID, PERSON_PERSON_PATIENT_ID, PERSON_PERSON_PRESCRIBER_ID,
                    PRESCRIBER_PCS_PCS_ID, CONSENT_BY_PERSON_PERSON_ID, MEDICATION_HEALTH_BEHAVIOR_INFO_ID,
                    ADD_PERSON_ID, ADD_ORGN_ID, MOD_PERSON_ID, MOD_ORGN_ID,
                    THRIVE_FAILURE_IND, DATE_UNKNOWN, MEDICATION_CMNT, DOSAGE_DESC,
                    CLN_RESP_ADVERSE_EFFECT_CMNT, CONSENT_COMMENTS,
                    START_DATE, END_DATE, LAST_REFILL_DATE, CONSENT_DATE,
                    ADD_TS, ADD_USER, MOD_TS, MOD_USER, CREATED_DATE, DELETED_DATE, CHECKSUM)
            VALUES (src.MHP_ID, src.MED_MED_ID, src.HPP_HPP_ID, src.PERSON_PERSON_PATIENT_ID, src.PERSON_PERSON_PRESCRIBER_ID,
                    src.PRESCRIBER_PCS_PCS_ID, src.CONSENT_BY_PERSON_PERSON_ID, src.MEDICATION_HEALTH_BEHAVIOR_INFO_ID,
                    src.ADD_PERSON_ID, src.ADD_ORGN_ID, src.MOD_PERSON_ID, src.MOD_ORGN_ID,
                    src.THRIVE_FAILURE_IND, src.DATE_UNKNOWN, src.MEDICATION_CMNT, src.DOSAGE_DESC,
                    src.CLN_RESP_ADVERSE_EFFECT_CMNT, src.CONSENT_COMMENTS,
                    src.START_DATE, src.END_DATE, src.LAST_REFILL_DATE, src.CONSENT_DATE,
                    src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER, src.CREATED_DATE, src.DELETED_DATE, src.CHECKSUM);

        rows_loaded := (SELECT $1 + $2 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''FACT_MEDICATION_HEALTH_BEHAVIOR load completed. Rows loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''FACT_MEDICATION_HEALTH_BEHAVIOR load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_FACT_PERSON_ORG_INVOLVEMENT"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_FACT_PERSON_ORG_INVOLVEMENT_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        MERGE INTO DCF_RAWDATA.DWH.FACT_PERSON_ORG_INVOLVEMENT tgt
        USING (
            SELECT poi.POI_ID, poi.IC_IC_ID, poi.CAS_CAS_ID, poi.INV_INV_ID,
                   poi.ORGN_ORGN_ID, poi.PERSON_PERSON_ID, poi.START_DATE, poi.END_DATE,
                   d.PERSON_ORG_INVOLVEMENT_INFO_ID, poi.ADD_TS, poi.ADD_USER, poi.MOD_TS, poi.MOD_USER,
                   CURRENT_TIMESTAMP() AS CREATED_DATE, poi.DELETED_DATE, poi.CHECKSUM, poi.SEARCHED_IND
            FROM DCF_RAWDATA.STAGING.STG_PERSON_ORG_INVOLVEMENT poi
            LEFT JOIN DCF_RAWDATA.DWH.DIM_PERSON_ORG_INVOLVEMENT_INFO d
                ON poi.REASON_CLOSED_CODE IS NOT DISTINCT FROM d.REASON_CLOSED_CODE_AV_ID
               AND d.UPDATED_DATE IS NULL
        ) src ON tgt.POI_ID = src.POI_ID
        WHEN MATCHED AND src.CHECKSUM <> tgt.CHECKSUM THEN
            UPDATE SET
                IC_IC_ID=src.IC_IC_ID, CAS_CAS_ID=src.CAS_CAS_ID, INV_INV_ID=src.INV_INV_ID,
                ORGN_ORGN_ID=src.ORGN_ORGN_ID, PERSON_PERSON_ID=src.PERSON_PERSON_ID,
                START_DATE=src.START_DATE, END_DATE=src.END_DATE,
                PERSON_ORG_INVOLVEMENT_INFO_ID=src.PERSON_ORG_INVOLVEMENT_INFO_ID,
                ADD_TS=src.ADD_TS, ADD_USER=src.ADD_USER, MOD_TS=src.MOD_TS, MOD_USER=src.MOD_USER,
                DELETED_DATE=src.DELETED_DATE, CHECKSUM=src.CHECKSUM, SEARCHED_IND=src.SEARCHED_IND
        WHEN NOT MATCHED THEN
            INSERT (POI_ID, IC_IC_ID, CAS_CAS_ID, INV_INV_ID, ORGN_ORGN_ID, PERSON_PERSON_ID,
                    START_DATE, END_DATE, PERSON_ORG_INVOLVEMENT_INFO_ID, ADD_TS, ADD_USER, MOD_TS, MOD_USER,
                    CREATED_DATE, DELETED_DATE, CHECKSUM, SEARCHED_IND)
            VALUES (src.POI_ID, src.IC_IC_ID, src.CAS_CAS_ID, src.INV_INV_ID, src.ORGN_ORGN_ID, src.PERSON_PERSON_ID,
                    src.START_DATE, src.END_DATE, src.PERSON_ORG_INVOLVEMENT_INFO_ID, src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER,
                    src.CREATED_DATE, src.DELETED_DATE, src.CHECKSUM, src.SEARCHED_IND);

        rows_loaded := (SELECT $1 + $2 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''FACT_PERSON_ORG_INVOLVEMENT load completed. Rows loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''FACT_PERSON_ORG_INVOLVEMENT load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';
CREATE OR REPLACE PROCEDURE "SP_DWH_FACT_PERSON_ROLE_ASSIGNMENTS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
    LET job_id STRING := (SELECT UUID_STRING());
    LET job_name STRING := ''DWH_FACT_PERSON_ROLE_ASSIGNMENTS_LOAD'';
    LET layer_name STRING := ''DWH'';
    LET start_time TIMESTAMP := CURRENT_TIMESTAMP();
    LET rows_loaded INTEGER := 0;

    BEGIN
        MERGE INTO DCF_RAWDATA.DWH.FACT_PERSON_ROLE_ASSIGNMENTS tgt
        USING (
            SELECT pra.PRA1_ID, pra.POI_POI_ID, d.PERSON_ROLE_ASSIGNMENTS_INFO_ID,
                   pra.START_DATE, pra.END_DATE, pra.ADD_TS, pra.ADD_USER, pra.MOD_TS, pra.MOD_USER,
                   CURRENT_TIMESTAMP() AS CREATED_DATE, pra.DELETED_DATE, pra.CHECKSUM
            FROM DCF_RAWDATA.STAGING.STG_PERSON_ROLE_ASSIGNMENTS pra
            LEFT JOIN DCF_RAWDATA.DWH.DIM_PERSON_ROLE_ASSIGNMENTS_INFO d
                ON pra.ROLE_TYPE IS NOT DISTINCT FROM d.ROLE_TYPE_AV_ID
               AND pra.ROLE_SUB_TYPE IS NOT DISTINCT FROM d.ROLE_SUB_TYPE_AV_ID
               AND d.UPDATED_DATE IS NULL
        ) src ON tgt.PRA1_ID = src.PRA1_ID
        WHEN MATCHED AND src.CHECKSUM <> tgt.CHECKSUM THEN
            UPDATE SET
                POI_POI_ID=src.POI_POI_ID, PERSON_ROLE_ASSIGNMENTS_INFO_ID=src.PERSON_ROLE_ASSIGNMENTS_INFO_ID,
                START_DATE=src.START_DATE, END_DATE=src.END_DATE,
                ADD_TS=src.ADD_TS, ADD_USER=src.ADD_USER, MOD_TS=src.MOD_TS, MOD_USER=src.MOD_USER,
                DELETED_DATE=src.DELETED_DATE, CHECKSUM=src.CHECKSUM
        WHEN NOT MATCHED THEN
            INSERT (PRA1_ID, POI_POI_ID, PERSON_ROLE_ASSIGNMENTS_INFO_ID, START_DATE, END_DATE,
                    ADD_TS, ADD_USER, MOD_TS, MOD_USER, CREATED_DATE, DELETED_DATE, CHECKSUM)
            VALUES (src.PRA1_ID, src.POI_POI_ID, src.PERSON_ROLE_ASSIGNMENTS_INFO_ID, src.START_DATE, src.END_DATE,
                    src.ADD_TS, src.ADD_USER, src.MOD_TS, src.MOD_USER, src.CREATED_DATE, src.DELETED_DATE, src.CHECKSUM);

        rows_loaded := (SELECT $1 + $2 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

        CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), :rows_loaded, 0, ''SUCCESS'', NULL);
        CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''SUCCESS'', :job_name, :layer_name, ''FACT_PERSON_ROLE_ASSIGNMENTS load completed. Rows loaded: '' || :rows_loaded);
        RETURN ''SUCCESS: '' || rows_loaded || '' rows loaded'';
    EXCEPTION
        WHEN OTHER THEN
            LET err STRING := SQLERRM;
            CALL DCF_RAWDATA.AUDIT.SP_LOG_AUDIT(:job_id, :job_name, :layer_name, :start_time, CURRENT_TIMESTAMP(), 0, 1, ''FAILED'', :err);
            CALL DCF_RAWDATA.UTIL.SP_SEND_PIPELINE_NOTIFICATION(''FAILED'', :job_name, :layer_name, ''FACT_PERSON_ROLE_ASSIGNMENTS load failed. Error: '' || :err);
            RETURN ''FAILED: '' || err;
    END;
END';