INSERT INTO DCF_RAWDATA.PUBLIC.TABLE_PK_CONFIG
(TABLE_NAME, PK_COLUMN, HAS_CHECKSUM)
VALUES
('T_PERSONS',                    'PERSON_ID', TRUE),
('T_CASES',                      'CAS_ID', TRUE),
('T_MEDICATIONS',                'MED_ID', TRUE),
('T_MEDICATION_HEALTH_BEHAVIOR', 'MHP_ID', TRUE),
('T_CUSTODIES',                  'CUS_ID', TRUE),
('T_PERSON_ORG_INVOLVEMENT',     'POI_ID', TRUE),
('T_PERSON_ROLE_ASSIGNMENTS',    'PRA1_ID', TRUE),
('T_ALLOWABLE_VALUES',           'AV_ID', FALSE);