


select * from staging.stg_person_role_assignments


TRUNCATE TABLE DIM_DM_CAS_CASES_DT;

TRUNCATE TABLE DIM_DM_CUS_CUSTODIES_DT;

TRUNCATE TABLE DIM_DM_MEDICATION_CONSENT_DETAILS_DT;

TRUNCATE TABLE FACT_DM_MEDICATION_CONSENT;