select * from  DCF_RAWDATA.CONFIG.ETL_WATERMARK

select * from DCF_RAWDATA.public.table_pk_config

SELECT LISTAGG(
           't.' || COLUMN_NAME || ' = s.' || COLUMN_NAME,
           ', '
       ) WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS SET_CLAUSE
FROM DCF_RAWDATA.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'PUBLIC'
  AND TABLE_NAME = 'T_PERSONS'
  AND COLUMN_NAME <> 'PERSON_ID';


  SELECT LISTAGG(
           COLUMN_NAME,
           ', '
       ) WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS COLUMN_LIST
FROM DCF_RAWDATA.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'PUBLIC'
  AND TABLE_NAME = 'T_PERSONS';