SELECT * FROM DCF_RAWDATA.PUBLIC.T_PERSONS 
WHERE PERSON_ID IN (14950557, 14952820);


REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_PERSON_ROLE_ASSIGNMENTS/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_PERSON_ORG_INVOLVEMENT/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_PERSONS/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_MEDICATION_HEALTH_BEHAVIOR/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_MEDICATIONS/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_CUSTODIES/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_CASES/';
REMOVE '@DCF_RAWDATA.RAWDATA.POSTGRES_STAGE/T_ALLOWABLE_VALUES/';

REMOVE '@"DCF_RAWDATA"."RAWDATA"."POSTGRES_STAGE"/T_MEDICATIONS_2.csv'




DELETE FROM DCF_RAWDATA.PUBLIC.T_CASES;

DELETE FROM DCF_RAWDATA.PUBLIC.T_CUSTODIES;

DELETE FROM DCF_RAWDATA.PUBLIC.T_MEDICATIONS;

DELETE FROM DCF_RAWDATA.PUBLIC.T_MEDICATION_HEALTH_BEHAVIOR;

DELETE FROM DCF_RAWDATA.PUBLIC.T_PERSONS;

DELETE FROM DCF_RAWDATA.PUBLIC.T_PERSON_ORG_INVOLVEMENT;

DELETE FROM DCF_RAWDATA.PUBLIC.T_PERSON_ROLE_ASSIGNMENTS;

DELETE FROM DCF_RAWDATA.PUBLIC.T_ALLOWABLE_VALUES;


DELETE FROM DCF_RAWDATA.CONFIG.ETL_FAILED_RECORDS;

DELETE FROM DCF_RAWDATA.CONFIG.ETL_WATERMARK where table_name='T_CUSTODIES'


select * from DCF_RAWDATA.CONFIG.ETL_WATERMARK;

CREATE OR REPLACE TABLE  DCF_RAWDATA.PUBLIC.INCREMENTAL_LOAD_WATERMARK (
    PIPELINE_NAME         VARCHAR(100)  PRIMARY KEY,
    LAST_FILE_NAME        VARCHAR(500),
    LAST_FILE_TS          TIMESTAMP_NTZ,
    LAST_LOADED_TIMESTAMP TIMESTAMP_NTZ,
    LAST_RUN_TS           TIMESTAMP_NTZ
);

INSERT INTO DCF_RAWDATA.PUBLIC.INCREMENTAL_LOAD_WATERMARK
    (PIPELINE_NAME, LAST_FILE_NAME, LAST_FILE_TS, LAST_LOADED_TIMESTAMP, LAST_RUN_TS)
VALUES
    ('INCREMENTAL_LOAD_RAWDATA', NULL, NULL, NULL, NULL);

select * from dcf_rawdata.public.incremental_load_watermark

INSERT INTO DCF_RAWDATA.PUBLIC.INCREMENTAL_LOAD_WATERMARK 
    (PIPELINE_NAME, LAST_FILE_NAME, LAST_FILE_TS, LAST_RUN_TS)
VALUES 
    ('INCREMENTAL_LOAD_RAWDATA', NULL, NULL, NULL);


select * from RETAIL_ETL_DB_NEW.AUDIT.AUDIT_JOB_LOG order by start_time desc
    
SELECT CAS_ID, ADD_TS, MOD_TS,
       GREATEST(ADD_TS, COALESCE(MOD_TS, ADD_TS)) AS EFF_TS
FROM DCF_RAWDATA.PUBLIC.T_CASES
WHERE CAS_ID = 9992;

select * from public.t_cases where cas_id=9992



UPDATE DCF_RAWDATA.PUBLIC.T_CASES SET CASE_TYPE = 'ADNew', MOD_TS = '2026-06-25 10:01:00', MOD_USER = 'TESTUSER', CHECKSUM = 'UPDCHK0024678' WHERE CAS_ID = 9992;


ALTER TABLE DCF_RAWDATA.PUBLIC.INCREMENTAL_LOAD_WATERMARK DROP COLUMN PROCESSED_FILES;
ALTER TABLE DCF_RAWDATA.PUBLIC.INCREMENTAL_LOAD_WATERMARK ADD COLUMN PROCESSED_FILES VARCHAR(10000);

select * from dcf_rawdata.rawdata.T

call DCF_RAWDATA.RAWDATA.SP_LOAD_RAW_TABLE('T_CASES')


CREATE OR REPLACE TABLE DCF_RAWDATA.PUBLIC.TABLE_PK_CONFIG (
    TABLE_NAME     VARCHAR,
    PK_COLUMN      VARCHAR,
    HAS_CHECKSUM   BOOLEAN
);

INSERT INTO DCF_RAWDATA.PUBLIC.TABLE_PK_CONFIG
(TABLE_NAME, PK_COLUMN, HAS_CHECKSUM)
VALUES
('T_PERSONS',                    'PERSON_ID', TRUE),
('T_CASES',                      'CAS_ID', TRUE),
('T_MEDICATIONS',                'MED_ID', TRUE),
('T_MEDICATION_HEALTH_BEHAVIOR', 'MHP_ID', TRUE),
('T_CUSTODIES',                  'CUS_ID', TRUE),
('T_PERSON_ORG_INVOLVEMENT',     'POI_ID', TRUE),
('T_PERSON_ROLE_ASSIGNMENTS',    'PRA1_ID', TRUE),
('T_ALLOWABLE_VALUES',           'AV_ID', FALSE);




create or replace schema AUDIT;

create or replace TABLE AUDIT_JOB_LOG (
	JOB_ID VARCHAR(16777216),
	JOB_NAME VARCHAR(16777216),
	LAYER_NAME VARCHAR(16777216),
	START_TIME TIMESTAMP_NTZ(9),
	END_TIME TIMESTAMP_NTZ(9),
	ROWS_PROCESSED NUMBER(38,0),
	ROWS_FAILED NUMBER(38,0),
	JOB_STATUS VARCHAR(16777216),
	ERROR_MESSAGE VARCHAR(16777216)
);



ALTER STAGE DCF_RAWDATA.RAWDATA.POSTGRES_STAGE
SET DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STREAM DCF_RAWDATA.RAWDATA.STREAM_POSTGRES_STAGE
ON STAGE DCF_RAWDATA.RAWDATA.POSTGRES_STAGE
-- how many total rows in T_CASES now
SELECT COUNT(*) FROM DCF_RAWDATA.PUBLIC.T_CASES;

-- check if CAS_IDs overlap between the two loads
SELECT MIN(CAS_ID), MAX(CAS_ID) FROM DCF_RAWDATA.PUBLIC.T_CASES;
SELECT * FROM DCF_RAWDATA.CONFIG.ETL_WATERMARK WHERE TABLE_NAME = 'T_CASES';



SELECT MIN(ADD_TS), MAX(ADD_TS), MIN(MOD_TS), MAX(MOD_TS) 
FROM DCF_RAWDATA.PUBLIC.T_CASES;


select * from DCF_RAWDATA.RAWDATA.STREAM_POSTGRES_STAGE

CREATE OR REPLACE TASK DCF_RAWDATA.PUBLIC.TASK_RAW_ORCHESTRATE
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE  = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('DCF_RAWDATA.RAWDATA.STREAM_POSTGRES_STAGE')
AS
CALL DCF_RAWDATA.PUBLIC.SP_ORCHESTRATE_RAW_LOAD();


select * from public.T_MEDICATION_HEALTH_BEHAVIOR



select * from public.T_ALLOWABLE_VALUES 

select * from DCF_RAWDATA.PUBLIC.T_PERSONS where PERSON_ID=14889763

select * from dcf_rawdata.config.etl_watermark

ALTER TASK DCF_RAWDATA.PUBLIC.TASK_RAW_ORCHESTRATE SUSPEND;

EXECUTE TASK DCF_RAWDATA.PUBLIC.TASK_RAW_ORCHESTRATE


SELECT COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION
FROM DCF_RAWDATA.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'PUBLIC'
  AND TABLE_NAME   = 'T_CASES'
ORDER BY ORDINAL_POSITION;

SELECT * FROM DCF_RAWDATA.PUBLIC.TABLE_PK_CONFIG
WHERE UPPER(TABLE_NAME) = 'T_CASES';


select from config.etl_watermark

create or replace TABLE T_ALLOWABLE_VALUES (
	AV_PK_ID NUMBER(10,0),
	AV_ID VARCHAR(10) NOT NULL,
	AVC_AVC_ID NUMBER(10,0),
	VALUE_CODE VARCHAR(10),
	VALUE_SHORT_DESC VARCHAR(80),
	VALUE_DEFAULT_IND VARCHAR(1),
	VALUE_RULE_NUM NUMBER(38,0),
	VALUE_SORT_ORDER_NUM NUMBER(38,0),
	ADD_TS TIMESTAMP_LTZ(9),
	ADD_USER VARCHAR(20),
	MOD_TS TIMESTAMP_TZ(9),
	MOD_USER VARCHAR(20),
	DISCONTINUED_DATE TIMESTAMP_NTZ(9),
	VALUE_LONG_DESC VARCHAR(240),
	MINIMUM_NUM VARCHAR(12),
	MAXIMUM_NUM VARCHAR(12),
	LOADED_DATE TIMESTAMP_LTZ(9),
	primary key (AV_ID)
);

-- clean all RAW tables
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_CUSTODIES;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_CASES;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_PERSONS;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_MEDICATIONS;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_MEDICATION_HEALTH_BEHAVIOR;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_PERSON_ORG_INVOLVEMENT;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_PERSON_ROLE_ASSIGNMENTS;
TRUNCATE TABLE DCF_RAWDATA.PUBLIC.T_ALLOWABLE_VALUES;

-- clean watermark
TRUNCATE TABLE DCF_RAWDATA.CONFIG.ETL_WATERMARK;

-- clean failed records
TRUNCATE TABLE DCF_RAWDATA.CONFIG.ETL_FAILED_RECORDS;


SELECT GET_DDL('SCHEMA', 'DCF_RAWDATA.PUBLIC');


DROP PROCEDURE IF EXISTS DCF_RAWDATA.PUBLIC.SP_LOAD_RAW_TABLE(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS DCF_RAWDATA.PUBLIC.SP_LOAD_RAW_TABLE(VARCHAR);
DROP PROCEDURE IF EXISTS DCF_RAWDATA.PUBLIC.SP_ORCHESTRATE_RAW_LOAD();


SELECT PROCEDURE_DEFINITION
FROM DCF_RAWDATA.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_NAME = 'SP_ORCHESTRATE_RAW_LOAD'
AND PROCEDURE_CATALOG = 'DCF_RAWDATA';


select * from public.t_cases where cas_id=3065248

SELECT CAS_ID, CASE_NAME, CHECKSUM, MOD_TS
FROM DCF_RAWDATA.PUBLIC.T_CASES 
WHERE CAS_ID = 3065248
ORDER BY MOD_TS;



SELECT m.*
FROM T_MEDICATIONS m
JOIN T_ALLOWABLE_VALUES av
    ON m.MEDICATION_CLASSIFICATION_CODE = av.AV_ID
LIMIT 100;

select * from dwh.fact_medications

select * from dwh.dim_medications_info

select * from PUBLIC.T_MEDICATIONS where MEDICATION_CLASSIFICATION_CODE is not null


select * from dwh.DIM_MEDICATIONS_INFO where medication_classification_code_av_id is not null



-- Fix duplicate records in FACT_MEDICATIONS by deduplicating DIM_MEDICATIONS_INFO join
-- Co-authored with CoCo

-- Step 1: Clean up duplicate rows in DIM_MEDICATIONS_INFO (keep only the lowest ID per classification code)
DELETE FROM DCF_RAWDATA.DWH.DIM_MEDICATIONS_INFO
WHERE MEDICATIONS_INFO_ID NOT IN (
    SELECT MIN(MEDICATIONS_INFO_ID)
    FROM DCF_RAWDATA.DWH.DIM_MEDICATIONS_INFO
    WHERE UPDATED_DATE IS NULL
    GROUP BY MEDICATION_CLASSIFICATION_CODE_AV_ID
)
AND UPDATED_DATE IS NULL;

-- Step 2: Load FACT_MEDICATIONS (now produces 1 row per medication, no duplicates)
SELECT
    m.MED_ID,
    d.MEDICATIONS_INFO_ID,
    m.COMMON_NAME,
    m.ROGER_DECISION_DRUG_IND,
    m.MEDICATION_DESC,
    m.ALLOW_FREQUENCY_NUM,
    m.ADD_PERSON_ID,
    m.ADD_ORGN_ID,
    m.MOD_PERSON_ID,
    m.MOD_ORGN_ID,
    m.ADD_TS,
    m.ADD_USER,
    m.MOD_TS,
    m.MOD_USER,
    CURRENT_TIMESTAMP() AS CREATED_DATE,
    m.DELETED_DATE
FROM STAGING.STG_MEDICATIONS m
INNER JOIN DWH.DIM_MEDICATIONS_INFO d
    ON m.MEDICATION_CLASSIFICATION_CODE = d.MEDICATION_CLASSIFICATION_CODE_AV_ID
    AND d.UPDATED_DATE IS NULL



SELECT TABLE_NAME, LAST_SUCCESSFUL_WATERMARK, UPDATED_AT 
FROM DCF_RAWDATA.CONFIG.ETL_WATERMARK 
WHERE TABLE_NAME = 'T_MEDICATIONS';